### ISSUE TITLE
Hare's dependencies on SSPL

### ISSUE THREAD

**Issue by vvv** [Seagate/cortx-hare#1167]
# Problem

Hare's dependencies on SSPL/RAS are poorly understood.

## Facts

(Terms SSPL and RAS are interchangeable.)

- SSPL monitors state of its node's hardware devices (e.g., SAS link disconnect/connect events).
- SSPL cannot detect node failures.  When a node is powered off, the SSPL that runs on that node is gone.  (On the picture below SSPL can detect 1, 3–6, but it cannot detect 2.  Consul can.)

![200729_sspl-failures](https://user-images.githubusercontent.com/17462/88787516-a6194a00-d19c-11ea-980e-ffbeb6ae81f4.png)

- SSPL will react to changes of state of the monitored hardware devices by putting messages (_alerts_ in SSPL vocabulary) into Kafka.

## Design notes

- SSPL won't be putting any events into Hare's EQ (event queue).
- Hare can read SSPL alerts from Kafka ..
- .. or HA ([cortx-ha](https://github.com/Seagate/cortx-ha)) may put events into Hare's EQ.
- Hare may configure Consul to put node offline/online events into the EQ.

cc @indrajitzagade, @rajanikantchirmade, @markwiggins-stx, @cdeshmukh, @ujjwalpl, @ajaysrivas

**Comment by indrajitzagade** [comment]
@vvv Can we close this PR?

**Comment by knekrasov** [comment]
@vvv has left Seagate.

@mssawant Do you have clear understanding how SSPL and Hare must interact?

**Comment by vvv** [comment]
cc @ajaysrivas

**Comment by cdeshmukh** [comment]
this is CortxV2 work as i see, can defer for time being.

**Comment by knekrasov** [comment]
Yes, @vaibhavparatwar, good point. Nowadays HA is integrated with SSPL, Hare has no direct dependency on SSPL.
Closing the ticket.

**Comment by cortx-admin** [comment]
> Vaibhav Prakash Paratwar commented in Jira Server:

.
