### ISSUE TITLE
Problem: no way for bash scripts to get relevant IP address where Hax web server is listening

### ISSUE THREAD

**Issue by azheregelya** [Seagate/cortx-hare#1248]
Hax gets IP for binding from consul:
`hax/server.py`
```
addr = ConsulUtil().get_hax_ip_address()
```

Having a use case when curl is used to access HTTP API endpoint, the request have to be sent to proper IP address. This issue is to find and way to do it.

Possible options so far:
1. Make hax to listen on INADDR_ANY by using `0.0.0.0` argument for webserver to bind.
Tested. It works. The cons here is that hax becomes accessible from all interfaces. This may be a problem for security.
2. Make hax to listen on `127.0.0.1`. This is opposite solution when only local processes can access HTTP API endpoint. Cons: it may break communication with other applications if they are communicating with hax via network.
3. Define a way how bash script can get hax IP from Consul.

**Comment by justinzw** [comment]
Jira ticket here: https://jts.seagate.com/browse/EOS-23768

Above we see this:
> Reopening issue to discuss it when time permits. So far, Option 1 was implemented and merged according to @knekrasov advise.

@knekrasov  does this mean that the issue was resolved?

**Comment by justinzw** [comment]
I'm going to ping @knekrasov on Jira to get a status update.

**Comment by vaibhavparatwar** [comment]
This information can be taken from hctl status. So closing this ticket. cc @mssawant

**Comment by cortx-admin** [comment]
> Vaibhav Prakash Paratwar commented in Jira Server:

Close this ticket [~534380]

**Comment by cortx-admin** [comment]
> Vaibhav Prakash Paratwar commented in Jira Server:

.

**Comment by cortx-admin** [comment]
> Vaibhav Prakash Paratwar commented in Jira Server:

.

**Comment by cortx-admin** [comment]
> Vaibhav Prakash Paratwar commented in Jira Server:

,
