### ISSUE TITLE
Problem: h0q doesn't ingest the payload from stdin

### ISSUE THREAD

**Issue by knekrasov** [Seagate/cortx-hare#1300]
The problem was discovered in scope of https://github.com/Seagate/cortx-hare/pull/1297 ([comment](https://github.com/Seagate/cortx-hare/pull/1297#discussion_r489095409))

It seems like the core problem is that payload is a **positional argument** and there is no way to instruct Click library to consume payload eagerly even if there are spaces and other separators.

Solution:
1. Make payload an option instead of argument (i.e. `h0q MY_MSG_TYPE --payload='$JSON'`)
2. Add possibility to pass the payload via stdin (e.g. `echo $JSON | h0q MY_MSG_TYPE`)

cc @chumakd, @mssawant

**Comment by justinzw** [comment]
> Answering to myself: no.
> 
> ```
> $ export payload='{ "this" : 1 }'
> $ h0q eq device-state-set $payload
> 2020-09-16 03:16:09,237 [ERROR] Exiting with failure
> Traceback (most recent call last):
>   File "/home/720599/projects/hare/hax/hax/queue/cli.py", line 52, in main
>     obj={})
>   File "/opt/seagate/cortx/hare/lib/python3.6/site-packages/click/core.py", line 829, in __call__
>     return self.main(*args, **kwargs)
>   File "/opt/seagate/cortx/hare/lib/python3.6/site-packages/click/core.py", line 781, in main
>     with self.make_context(prog_name, args, **extra) as ctx:
>   File "/opt/seagate/cortx/hare/lib/python3.6/site-packages/click/core.py", line 700, in make_context
>     self.parse_args(ctx, args)
>   File "/opt/seagate/cortx/hare/lib/python3.6/site-packages/click/core.py", line 1053, in parse_args
>     "s" if len(args) != 1 else "", " ".join(map(make_str, args))
>   File "/opt/seagate/cortx/hare/lib/python3.6/site-packages/click/core.py", line 550, in fail
>     raise UsageError(message, self)
> click.exceptions.UsageError: Got unexpected extra arguments ("this" : 1 })
> ```
> 
> ```
> h0q eq device-state-set "$payload"
> 2020-09-16 03:16:15,454 [DEBUG] Attempting to invoke the repeatable call: publish
> 2020-09-16 03:16:15,458 [DEBUG] Starting new HTTP connection (1): 127.0.0.1:8500
> 2020-09-16 03:16:15,459 [DEBUG] http://127.0.0.1:8500 "GET /v1/kv/eq-epoch HTTP/1.1" 200 105
> 2020-09-16 03:16:15,466 [DEBUG] http://127.0.0.1:8500 "PUT /v1/txn HTTP/1.1" 200 146
> 2020-09-16 03:16:15,467 [DEBUG] The repeatable call succeeded: publish
> 2020-09-16 03:16:15,467 [INFO] Written to epoch: 805
> ```
> 
@mssawant @knekrasov  is there any update on this issue? Just wondering what the current status is.

**Comment by mssawant** [comment]
@justinzw,
Sorry, we have not scheduled this task yet, Hare team is short on bandwidth presently. Let me take this up in our next scrum meeting. From the comments it seems the fix is straightforward; thus, it should not take much time. cc @vaibhavparatwar

**Comment by cortx-admin** [comment]
> Vaibhav Prakash Paratwar commented in Jira Server:

[~930816] please investigate. cc [~520513] [~520478]

**Comment by vaibhavparatwar** [comment]
@mssawant what is the priority of this issue?

**Comment by cortx-admin** [comment]
> Vaibhav Prakash Paratwar commented in Jira Server:

Right now reducing the priority. We will revisit priority in upcoming sprints. cc [~520513] [~520478]

**Comment by shailesh-vaidya** [comment]
Closing as an obsolete
