### ISSUE TITLE
Problem: hare-{repair,rebalance} don't use private IP addresses when communicating to hax

### ISSUE THREAD

**Issue by knekrasov** [Seagate/cortx-hare#1302]
As of #1301 hax doesn't listen to `0.0.0.0` and thus it is not accessible via `localhost`. 
`hare-repair` and `hare-rebalance` must learn the virtual address of the current node first to use it in their CURL invocations.

Suggestion: re-implement the mentioned scripts in Python and leverage [hax/util.py](https://github.com/Seagate/cortx-hare/blob/dev/hax/hax/util.py) from hax module. Motivation:
1. There is [get_hax_ip_address()](https://github.com/Seagate/cortx-hare/blob/b3bcf80812f796549fe00293f2c5c58c8e63d6bd/hax/hax/util.py#L267) function which does all the magic
2. There is a [auto-retry mechanism](https://github.com/Seagate/cortx-hare/blob/b3bcf80812f796549fe00293f2c5c58c8e63d6bd/hax/hax/util.py#L85) for redundant and fault-tolerant communication to Consul.

**Comment by vaibhavparatwar** [comment]
@knekrasov is this issue still valid?

**Comment by knekrasov** [comment]
@vaibhavparatwar In fact, yes. SNS operations were implemented but not officially supported by current version of CORTX. Once we get back to this feature, this problem will have to be resolved somehow.

**Comment by justinzw** [comment]
closing this issue as the SNS feature has been backlogged per this comment ->

https://github.com/Seagate/cortx-hare/issues/1258#issuecomment-959677011

**Comment by cortx-admin** [comment]
> Vaibhav Prakash Paratwar commented in Jira Server:

Its addressed recently in https://jts.seagate.com/browse/CORTX-29486

**Comment by cortx-admin** [comment]
> Vaibhav Prakash Paratwar commented in Jira Server:

.

**Comment by cortx-admin** [comment]
> Vaibhav Prakash Paratwar commented in Jira Server:

.
