### ISSUE TITLE
Problem: 300 people have push access to the main repository

### ISSUE THREAD

**Issue by vvv** [Seagate/cortx-hare#1333]
Currently three hundred people can create new branches in [Seagate/cortx-hare](https://github.com/Seagate/cortx-hare) repository:

![Base role = Write](https://user-images.githubusercontent.com/17462/93709379-7c4e2500-fb46-11ea-9d7d-405303d8c41e.png)

And [they](https://github.com/Seagate/cortx-hare/pull/1290#discussion_r487905512) [do](https://github.com/Seagate/cortx-hare/pull/1332#issuecomment-695770705).

---

It is a strict requirement of Hare's development process that pull requests are created from personal forks.

[PC3](https://github.com/Seagate/cortx-hare/blob/dev/rfc/9/README.md#23-development-process):
> ### 2.3. Development Process
>
> \[...\]
>
> 6. To work on an issue, a Contributor SHALL fork the project repository and then work on their forked repository.

[CONTRIBUTING.md](https://github.com/Seagate/cortx-hare/blob/32dfe574636ca24d8d3829fb23acd6373eef48d1/CONTRIBUTING.md#sending-patches):
> ### Sending patches
>
> 0. [Fork](https://guides.github.com/activities/forking/) the repository (once).

---

[Read](https://docs.github.com/en/github/setting-up-and-managing-organizations-and-teams/repository-permission-levels-for-an-organization#repository-access-for-each-permission-level) permission level is sufficient to make a contribution — open an issue, fork Seagate/cortx-hare, and create a pull request.  Write permission level should be restricted.

> ### [2.1. Preliminaries](https://github.com/Seagate/cortx-hare/blob/dev/rfc/9/README.md#21-preliminaries)
>
> \[...\]
>
> 5. A "Contributor" is a person who wishes to provide a patch, being a set of commits that solve some clearly identified problem.
>
> 6. A "Maintainer" is a person who merges patches to the project. Maintainers are not developers; their job is to enforce process.
>
> 7. A "Reviewer" is a person who reviews patches and who has deep familiarity with the code base.
>
> 8. Contributors SHALL NOT have commit access to the repository unless they are also Maintainers.
>
> 9. Maintainers SHALL have commit access to the repository.
>
> 10. Reviewers SHALL NOT have commit access to the repository unless they are also Maintainers.
>
> 11. Everyone, without distinction or discrimination, SHALL have an equal right to become a Contributor under the terms of this contract.

Note stanzas 2.1.8 and 2.1.9.

**Solution:** change base role permission level to `Read`.

**Comment by vaibhavparatwar** [comment]
I think we can close this now? @mukul-seagate11 @xahmad ?

**Comment by knekrasov** [comment]
Was the issue resolved?
