### ISSUE TITLE
[No need to] Add SECURITY and SUPPORT files

### ISSUE THREAD

**Issue by Saumya-Sunder** [Seagate/cortx-hare#1340]
Hey @vvv we need to add two new files to the root folder : [SECURITY.md](https://github.com/Seagate/cortx/blob/main/SECURITY.md)  and [SUPPORT.md](https://github.com/Seagate/cortx/blob/main/SUPPORT.md)

Please refer to [Issue # 310](https://github.com/Seagate/cortx/issues/310). We have added it to the rest of the repos. Could you please add these?

**Comment by vvv** [comment]
Mmm, it doesn't look like https://github.com/Seagate/cortx/issues/310 is related...

@Saumya-Sunder May I ask you to create a pull request?  See [Sending patches](https://github.com/Seagate/cortx-hare/blob/0ef78d4756b0dbccad66fe2c9c64807b32276ca4/CONTRIBUTING.md#sending-patches) section of Hare's `CONTRIBUTING.md`.  If you need help, we can have a screen sharing session.  Thank you.

**Comment by vvv** [comment]
@Saumya-Sunder 🕣 It's 20:34 IST, so I guess your work day is over. Could you at least describe me, what problem is solved by addition of SECURITY and SUPPORT files?

> 2. A patch SHOULD be a minimal and accurate answer to exactly one identified and agreed problem.

> 6. A patch commit message SHOULD consist of a single short (less than 50 characters) line stating the problem ("Problem: ...") being solved, followed by a blank line and then the proposed solution ("Solution: ...").

**Comment by Saumya-Sunder** [comment]
@vvv [This is the ask](https://docs.github.com/en/github/building-a-strong-community/creating-a-default-community-health-file) since the repos are not linked to CORTX we need to add these files individually to each repo.

**Comment by Saumya-Sunder** [comment]
@gauravchaudhari02 @mukul-seagate11 : I do not see the CONTRIBUTING.md file popping up while creating a PR. Both @vvv and I tested it. Could you help us fix this issue? I have put SUPPORT and SECURITY file uploads on hold. Also let me know if I can schedule a meeting between all four of us at a suitable time on Monday to fix this?

**Comment by vvv** [comment]
When I'm creating a pull request for <b>cortx</b> repository, there is a popup with “Contributing guidelines” link.
<details>
<summary>Screenshot 1</summary>

![cortx PR](https://user-images.githubusercontent.com/17462/94185279-c5d3a280-fead-11ea-8c66-23fc8bbb5b95.png)

</details>

When I'm creating a pull request for <b>cortx-hare</b>, there is no popup.
<details>
<summary>Screenshot 2</summary>

![cortx-hare PR](https://user-images.githubusercontent.com/17462/94185020-755c4500-fead-11ea-8c79-278c742e33d7.png)

</details>

@gauravchaudhari02, @mukul-seagate11 Can you explain this difference in the UI?

---

Both [**cortx**](https://github.com/Seagate/cortx) and [**cortx-hare**](https://github.com/Seagate/cortx-hare) repositories have `CONTRIBUTING.md` files.

From [Creating a default community health file](https://docs.github.com/en/github/building-a-strong-community/creating-a-default-community-health-file) article:

> For example, anyone who creates an issue or pull request in a public repository that does not have its own CONTRIBUTING file will see a link to the default CONTRIBUTING file.

**Comment by vvv** [comment]
> since the repos are not linked to CORTX we need to add these files individually to each repo.

@mukul-seagate11 Can you explain what “linking a repository to CORTX” means?

**Comment by vvv** [comment]
Ah, I got it! 💡 

[About default community health files](https://docs.github.com/en/github/building-a-strong-community/creating-a-default-community-health-file#about-default-community-health-files):

> You can add default community health files to the root of a public repository called `.github` that is owned by an organization or user account.

@mukul-seagate11 @gauravchaudhari02 @Saumya-Sunder We need to create a public https://github.com/Seagate/.github repository and populate it with the required files — `CODE_OF_CONDUCT.md`, `CONTRIBUTING.md`, [etc.](https://docs.github.com/en/github/building-a-strong-community/creating-a-default-community-health-file#supported-file-types)

cc @johnbent

**Comment by gauravchaudhari02** [comment]
@vvv, We cannot create `.github` repository at an organization level as it would have documents specific to `cortx` and it would be a bad idea as we also have repositories from other teams. Those repositories will get cortx document  pop-ups unnecessarily.

e.g:

![image](https://user-images.githubusercontent.com/61046500/94783576-81cf2900-03ea-11eb-9a5e-edae4a3c51da.png)

**Comment by johnbent** [comment]
@gauravchaudhari02 plus @xahmad : if we use the default .github approach, then the CORTX specific health files will show up for all repo's in Seagate.  Great for CORTX!  Maybe OK for some other Seagate repos maybe a bit annoying for some other repos.  But if some other repo doesn't like it, then can't they just create their own files which will override the default ones in the default .github folder?  @xahmad , assuming this is correct, you cool with this?

**Comment by gauravchaudhari02** [comment]
> @gauravchaudhari02 plus @xahmad : if we use the default .github approach, then the CORTX specific health files will show up for all repo's in Seagate. Great for CORTX! Maybe OK for some other Seagate repos maybe a bit annoying for some other repos. But if some other repo doesn't like it, then can't they just create their own files which will override the default ones in the default .github folder? @xahmad , assuming this is correct, you cool with this?

@xahmad, Could we get your opinion on above please?

**Comment by xahmad** [comment]
Yes, I love the idea of an org level specific health files. 

As long as the language is not Cortx specific and general, that will be a great addition!

**Comment by gauravchaudhari02** [comment]
@johnbent, Could you please comment here?

**Comment by johnbent** [comment]
If we can add them at the org level, then let’s please do so. If we can’t, please go ahead and merge this in to each child repo. 

I think our files are CORTX specific so I think we have to add at each individual repo...

**Comment by gauravchaudhari02** [comment]
@johnbent, We already have it at the org level, but as the file data is CORTX related, we might need to add it to each CORTX child repository. 
Again, would it be good to move the `CODE-OF-CONDUCT`,`CONTRIBUTING.md` files of each component inside the `.github` folder?

**Comment by vvv** [comment]
@gauravchaudhari02 I've left Seagate. ⛵️ 

@azheregelya Can you take this over (or delegate to someone) please?

**Comment by gauravchaudhari02** [comment]
> @gauravchaudhari02 I've left Seagate. ⛵️
> 
> @azheregelya Can you take this over (or delegate to someone) please?

@vvv, sad to hear that 😞 But we are opensource now. so you could give your expert suggestion 🙂

**Comment by vvv** [comment]
> would it be good to move the `CODE-OF-CONDUCT`, `CONTRIBUTING.md` files of each component inside the .github folder?

@gauravchaudhari02 No, we don't want to _hide_ `CONTRIBUTING.md`.

**Comment by azheregelya** [comment]
@gauravchaudhari02 Hiding `CONTIRUBUTING.md` is bad idea, since this file is **expected to be read** before "Create pull request" button is hit. Therefore it should be **noticeable** and placed in **expected** location (which is root folder in our case).

`.github` folder is apparently Github related feature which can be a problem for people and companies who want to host the fork of this repo in alternative source code management systems. 
We don't want to introduce vendor-lock-like obstacles for open-source community, right?

I'm personally fine to see `CODE_OF_CONDUCT.md` removed from current repo and kept only in Org-wide `.github` repository since both files looks equal. This Github feature lets us to avoid efforts in case CoC is updated - changes will be fetched from Org-wide repo.
Or we can just keep things as is to end up this issue. 

cc: @johnbent @vvv

**Comment by gauravchaudhari02** [comment]
@azheregelya, Agree with you 👍🏼   We can keep `CODE_OF_CONDUCT.md` in org wide `.github` and other files as it is.
What is your thought @johnbent?

**Comment by johnbent** [comment]
Yes, this makes sense @gauravchaudhari02 .  Thanks!

**Comment by Saumya-Sunder** [comment]
@gauravchaudhari02 can I move this to the .git folder you created the last time? I am assuming that I need to delete the CODE_OF_CONDUCT file from all repos if this is moved? @johnbent please confirm?

**Comment by gauravchaudhari02** [comment]
> @gauravchaudhari02 can I move this to the .git folder you created the last time? I am assuming that I need to delete the CODE_OF_CONDUCT file from all repos if this is moved? @johnbent please confirm?

@Saumya-Sunder, Yes. you can delete it as CODE_OF_CONDUCT is now at org level `.github` repository.

**Comment by Saumya-Sunder** [comment]
Done @gauravchaudhari02
