### ISSUE TITLE
Cortx-Hare build is failed (main branch)

### ISSUE THREAD

**Issue by imvenkip** [Seagate/cortx-hare#1374]
http://eos-jenkins.mero.colo.seagate.com/job/GitHub-custom-ci-builds/job/custom_build_test/job/hare-custom-build/2314/console

3:34:19  Compiling /root/rpmbuild/BUILDROOT/cortx-hare-1.0.0-2314_git3e0b565.el7.x86_64/opt/seagate/cortx/hare/conf/setup.py ...
13:34:19    File "/opt/seagate/cortx/hare/conf/setup.py", line 34
13:34:19      def get_data_from_provisioner_cli(method, output_format='json') -> str:
13:34:19                                                                      ^
13:34:19  SyntaxError: invalid syntax
13:34:19  
13:34:19  Compiling /root/rpmbuild/BUILDROOT/cortx-hare-1.0.0-2314_git3e0b565.el7.x86_64/opt/seagate/cortx/hare/lib/python3.6/site-packages/async_timeout/__init__.py ...
13:34:19    File "/opt/seagate/cortx/hare/lib/python3.6/site-packages/async_timeout/__init__.py", line 27
13:34:19      def __init__(self, timeout: Optional[float],
13:34:19                                ^
13:34:19  SyntaxError: invalid syntax
13:34:19  
13:34:19  Compiling /root/rpmbuild/BUILDROOT/cortx-hare-1.0.0-2314_git3e0b565.el7.x86_64/opt/seagate/cortx/hare/lib/python3.6/site-packages/attr/_next_gen.py ...
13:34:19    File "/opt/seagate/cortx/hare/lib/python3.6/site-packages/attr/_next_gen.py", line 18
13:34:19      *,
13:34:19       ^
13:34:19  SyntaxError: invalid syntax
13:34:19  
13:34:19  Compiling /root/rpmbuild/BUILDROOT/cortx-hare-1.0.0-2314_git3e0b565.el7.x86_64/opt/seagate/cortx/hare/lib/python3.6/site-packages/consul/aio.py ...
13:34:19    File "/opt/seagate/cortx/hare/lib/python3.6/site-packages/consul/aio.py", line 17
13:34:19      def __init__(self, *args, loop=None, **kwargs):
13:34:19                                   ^
13:34:19  SyntaxError: invalid syntax

**Comment by suvratjoshi** [comment]
Confirmed with @imvenkip 
This issue can be closed.
The custom build is passed without errors :
http://eos-jenkins.colo.seagate.com/job/GitHub-custom-ci-builds/job/centos-7.8/job/cortx-custom-ci/315/
Thanks!
