### ISSUE TITLE
hax: to send periodic keepalive msgs to m0clients

### ISSUE THREAD

**Issue by andriytk** [Seagate/cortx-hare#1385]
Currently, `hax` does not finish `ha_link`(s) with m0_client processes as these processes are not monitored by Consul and NC_FAILED is not sent for them when they disconnect or die unexpectedly. This may result in Motr RM-resources leakage or dead-locks or some other nasty things.

Suggested solution: `hax` can send periodically (once a second, for example) keepalive msgs to its m0_client processes and if there is no reply - do NC_FAILED on their `ha_link`(s).

#1383 depends on this.

Ref. [EOS-14689](https://jts.seagate.com/browse/EOS-14689)

**Comment by andriytk** [comment]
cc @mssawant , @madhavemuri , @NeeravChoudhari

**Comment by cortx-admin** [comment]
> Vaibhav Prakash Paratwar commented in Jira Server:

Closing this as we have https://jts.seagate.com/browse/CORTX-14689 this story ticket created for the issue.

**Comment by cortx-admin** [comment]
> Vaibhav Prakash Paratwar commented in Jira Server:

Duplicated

**Comment by cortx-admin** [comment]
> Vaibhav Prakash Paratwar commented in Jira Server:

.

**Comment by cortx-admin** [comment]
> Vaibhav Prakash Paratwar commented in Jira Server:

.
