### ISSUE TITLE
hare Run I/O test m0crate: command not found

### ISSUE THREAD

**Issue by yanqingfu** [Seagate/cortx-hare#1391]
![image](https://user-images.githubusercontent.com/68423216/97669562-5742bf80-1abf-11eb-8dd2-c5b3688f7135.png)

> [root@ssc-vm-1061 hare]# hctl bootstrap --mkfs singlenode.yaml
> 2020-10-30 00:36:02: Generating cluster configuration... OK
> 2020-10-30 00:36:03: Starting Consul server on this node............ OK
> 2020-10-30 00:36:13: Importing configuration into the KV store... OK
> 2020-10-30 00:36:15: Starting Consul on other nodes... OK
> 2020-10-30 00:36:15: Updating Consul configuraton from the KV store... OK
> 2020-10-30 00:36:15: Waiting for the RC Leader to get elected....... OK
> 2020-10-30 00:36:20: Starting Motr (phase1, mkfs)... OK
> 2020-10-30 00:36:48: Starting Motr (phase1, m0d)... OK
> 2020-10-30 00:36:52: Starting Motr (phase2, mkfs)... OK
> 2020-10-30 00:38:00: Starting Motr (phase2, m0d)... OK
> 2020-10-30 00:38:04: Checking health of services... OK
> [root@ssc-vm-1061 hare]# hctl status
> Data pool:
>     # fid name
>     0x6f00000000000001:0x22 'the pool'
> Profile:
>     # fid name: pool(s)
>     0x7000000000000001:0x3c 'default': 'the pool' None None
> Services:
>     localhost  (RC)
>     [started]  hax        0x7200000000000001:0x6   10.230.247.0@tcp:12345:1:1
>     [started]  confd      0x7200000000000001:0x9   10.230.247.0@tcp:12345:2:1
>     [started]  ioservice  0x7200000000000001:0xc   10.230.247.0@tcp:12345:2:2
>     [unknown]  m0_client  0x7200000000000001:0x1c  10.230.247.0@tcp:12345:4:1
>     [unknown]  m0_client  0x7200000000000001:0x1f  10.230.247.0@tcp:12345:4:2
> [root@ssc-vm-1061 hare]# /opt/seagate/cortx/hare/libexec/m0crate-io-conf >/tmp/m0crate-io.yaml
> Usage: grep [OPTION]... PATTERN [FILE]...
> Try 'grep --help' for more information.
> Usage: grep [OPTION]... PATTERN [FILE]...
> Try 'grep --help' for more information.
> [root@ssc-vm-1061 hare]# dd if=/dev/urandom of=/tmp/128M bs=1M count=128
> 128+0 records in
> 128+0 records out
> 134217728 bytes (134 MB) copied, 0.961014 s, 140 MB/s
> [root@ssc-vm-1061 hare]# m0crate -S /tmp/m0crate-io.yaml
> -bash: m0crate: command not found
> [root@ssc-vm-1061 hare]# /opt/seagate/cortx/hare/libexec/m0crate-io-conf > /tmp/m0crate-io.yaml
> Usage: grep [OPTION]... PATTERN [FILE]...
> Try 'grep --help' for more information.
> Usage: grep [OPTION]... PATTERN [FILE]...
> Try 'grep --help' for more information.
> [root@ssc-vm-1061 hare]# m0crate -S /tmp/m0crate-io.yaml
> -bash: m0crate: command not found
> [root@ssc-vm-1061 hare]# cd libexec/m0crate-io-conf
> -bash: cd: libexec/m0crate-io-conf: No such file or directory
> [root@ssc-vm-1061 hare]# cd libexec
> -bash: cd: libexec: No such file or directory
> [root@ssc-vm-1061 hare]# ls
> AUTHORS  CODE_OF_CONDUCT.md  hare.spec  hctl     Jenkinsfile  Makefile      README.md  rules            stubs    utils   VERSION
> cfgen    CONTRIBUTING.md     hax        jenkins  LICENSE      provisioning  rfc        singlenode.yaml  systemd  vendor
> [root@ssc-vm-1061 hare]# /opt/seagate/cortx/hare/utils/m0crate-io-conf > /tmp/m0crate-io.yaml
> -bash: /opt/seagate/cortx/hare/utils/m0crate-io-conf: No such file or directory
> [root@ssc-vm-1061 hare]# ls
> AUTHORS  CODE_OF_CONDUCT.md  hare.spec  hctl     Jenkinsfile  Makefile      README.md  rules            stubs    utils   VERSION
> cfgen    CONTRIBUTING.md     hax        jenkins  LICENSE      provisioning  rfc        singlenode.yaml  systemd  vendor
> [root@ssc-vm-1061 hare]# /utils/m0crate-io-conf > /tmp/m0crate-io.yaml
> -bash: /utils/m0crate-io-conf: No such file or directory
> [root@ssc-vm-1061 hare]# cd utils
> [root@ssc-vm-1061 utils]# ls
> bootstrap-node        gen-uuid            h0q               hare-node-join  hare-status      next-epoch  README.md
> check-service         get-entrypoint      hare-bootstrap    hare-reportbug  m0crate-io-conf  node-name   s3auth-disable
> consul-watch-handler  get-process-state   hare-drive-state  hare-shutdown   m0trace-prune    pcs-chart   update-consul-conf
> elect-rc-leader       get-service-health  hare-node         hare-start      mk-consul-env    proto-rc
> [root@ssc-vm-1061 utils]# ls
> bootstrap-node        gen-uuid            h0q               hare-node-join  hare-status      next-epoch  README.md
> check-service         get-entrypoint      hare-bootstrap    hare-reportbug  m0crate-io-conf  node-name   s3auth-disable
> consul-watch-handler  get-process-state   hare-drive-state  hare-shutdown   m0trace-prune    pcs-chart   update-consul-conf
> elect-rc-leader       get-service-health  hare-node         hare-start      mk-consul-env    proto-rc
> [root@ssc-vm-1061 utils]# m0crate-io-conf > /tmp/m0crate-io.yaml
> -bash: m0crate-io-conf: command not found
> [root@ssc-vm-1061 utils]# ./m0crate-io-conf > /tmp/m0crate-io.yaml
> Usage: grep [OPTION]... PATTERN [FILE]...
> Try 'grep --help' for more information.
> Usage: grep [OPTION]... PATTERN [FILE]...
> Try 'grep --help' for more information.
> [root@ssc-vm-1061 utils]# dd if=/dev/urandom of=/tmp/128M bs=1M count=128
> 128+0 records in
> 128+0 records out
> 134217728 bytes (134 MB) copied, 1.007 s, 133 MB/s
> [root@ssc-vm-1061 utils]# m0crate -S /tmp/m0crate-io.yaml
> -bash: m0crate: command not found

**Comment by suvratjoshi** [comment]
Here, the specific path m0crate needs to be given.
This command works well (path lies in the cortx-motr directory)
'''
./cortx-motr/motr/m0crate/m0crate  -S /tmp/m0crate-io.yaml
'''
This looks to be fix in documentation only.

**Comment by yanqingfu** [comment]
./motr/m0crate/m0crate -S /tmp/m0crate-io.yaml works
