### ISSUE TITLE
Problem: hax runs fs-stats updater on all cluster nodes

### ISSUE THREAD

**Issue by andriytk** [Seagate/cortx-hare#1406]
There are 16 client nodes on the SAGE cluster and 6 server nodes - and on all of them `hax` runs fs-stats updater:

```
17:04 tkachuk1@client-22:~$ sudo journalctl -lf | grep 'fs-stats-updater.*rconfc'
Nov 24 17:04:37 client-22 hare-hax[18380]: 2020-11-24 17:04:37,722 [DEBUG] {fs-stats-updater} Starting rconfc
Nov 24 17:04:38 client-22 hare-hax[18380]: 2020-11-24 17:04:38,692 [DEBUG] {fs-stats-updater} rconfc started
Nov 24 17:04:40 client-22 hare-hax[18380]: 2020-11-24 17:04:40,096 [DEBUG] {fs-stats-updater} Stopping rconfc
Nov 24 17:05:10 client-22 hare-hax[18380]: 2020-11-24 17:05:10,192 [DEBUG] {fs-stats-updater} Starting rconfc
Nov 24 17:05:11 client-22 hare-hax[18380]: 2020-11-24 17:05:11,125 [DEBUG] {fs-stats-updater} rconfc started
Nov 24 17:05:12 client-22 hare-hax[18380]: 2020-11-24 17:05:12,569 [DEBUG] {fs-stats-updater} Stopping rconfc
...
```

It does not only spam the system log, but also generates a redundant load on Consul (by updating the stats from each node in KV Store) and Motr.

Suggestion: modify `hax` code so that it runs fs-stats updater only on the RC-leader server node. On each iteration, `hax` can check whether it's running on RC-leader node by looking at the `leader` key in the KV Store and compare its value with `node-name`.

**Comment by andriytk** [comment]
cc @NeeravChoudhari, @mssawant, @chumakd, @azheregelya, @nikitadanilov.

**Comment by knekrasov** [comment]
Even though the concern in the ticket description is valid, it doesn't sound like an urgent issue. 

The only thing that I can miss in this judgement is additional Motr fops that fs-stats-updater thread generates (I just have no idea how fragile Motr is to this kind of load).
@NeeravChoudhari can you give your opinion on the priority of this issue?

**Comment by andriytk** [comment]
@knekrasov 
> ... generates a redundant load on Consul (by updating the stats from each node in KV Store) ...

**Comment by knekrasov** [comment]
"Redundant" doesn't mean "makes us slow and causes issues". That's why I'm not sure about the priority.

**Comment by andriytk** [comment]
If it doesn't now - it will. It's a scalability issue. It's not urgent, but it must be fixed.
