### ISSUE TITLE
Problem: refactor wait_for_all/wait_for_any in DeliveryHerald class to avoid code duplication

### ISSUE THREAD

**Issue by knekrasov** [Seagate/cortx-hare#1407]
As of https://github.com/Seagate/cortx-hare/pull/1400 DeliveryHerald class contains one more method wait_for_all (in addition to previously introduced wait_for_any). The code seems to be mostly a copy-paste. It seems like those two methods can be refactored to have basic logic: how to block, how to wait until a some predicate is True etc. And these two methods can simply provide different predicates.

The less code we have, the less chance we have to introduce a bug.

**Comment by gshipra** [comment]
This issue is fixed as part of EOS-16167

**Comment by knekrasov** [comment]
Resolved in scope of #1449
