### ISSUE TITLE
Problem: there is no verbose mode in hctl-shutdown

### ISSUE THREAD

**Issue by knekrasov** [Seagate/cortx-hare#1423]
This is a maintenance issue. Without verbose output it is hard to understand what went wrong when the script is used in the field.

Solution:
1. Start using `logging` library instead of explicit `print()` calls.
2. Log with different levels of verbosity: normal output (i.e. what we output with `print()` at the moment) goes with INFO, but some debugging, more informative and verbose stuff will go with DEBUG level.
3. Add `-v` CLI flag to enable DEBUG level of logging.

**Comment by SwapnilGaonkar7** [comment]
https://jts.seagate.com/browse/EOS-15932

**Comment by vaibhavparatwar** [comment]
Closing as taken care in https://jts.seagate.com/browse/EOS-15932
