### ISSUE TITLE
make devinstall does not work

### ISSUE THREAD

**Issue by andriytk** [Seagate/cortx-hare#1425]
Following https://github.com/Seagate/cortx-hare#installation:

```
[vagrant@cmu hare]$ sudo make devinstall
...
--> Installing hax with 'source /data/hare/.py3venv/bin/activate; python3.6 setup.py develop --prefix /opt/seagate/cortx/hare'
Traceback (most recent call last):
  File "setup.py", line 141, in <module>
    library_dirs=[get_motr_libs_dir()],
  File "setup.py", line 97, in get_motr_libs_dir
    assert P.isfile(libmotr), f'{libmotr}: No such file'
AssertionError: /data/cortx-motr/motr/.libs/libmotr.so: No such file
make: *** [/opt/seagate/cortx/hare/lib/python3.6/site-packages/hax.egg-link] Error 1
```

Commit 571ae39

**Comment by andriytk** [comment]
Looks like the regression was introduced at commit 69540388103088d902110375c723e9154cb31913.

cc @knekrasov

**Comment by andriytk** [comment]
Looks like the correct command should be `sudo sh -c 'export M0_SRC_DIR=/data/motr; make devinstall'`.

**Comment by mssawant** [comment]
I think by default it checks cortx-motr at `../HARE_SRC`. I have created a symlink to cortx-motr at `../HARE_SRC`.
This failure can be seen also when cortx-motr is not compiled.
