### ISSUE TITLE
Make Spiel object global

### ISSUE THREAD

**Issue by knekrasov** [Seagate/cortx-hare#1438]
Currently, fs-stats-updater thread starts and stops rconfc by itself. Given in R2 we'll also need to support SNS operations, Spiel context must be handled differently.

Please note that SNS-related operations are processed in ConsumerThread. Effectively SNS operation goes down to this function from `hax.c`:
{code:c}
static int spiel_sns_op(enum m0_cm_op sns_copy_machine_op,
			unsigned long long ctx,
			const struct m0_fid *pool_fid,
			struct m0_spiel_repreb_status **sns_statuses)
{
	struct hax_context *hc = (struct hax_context *)ctx;
	struct m0_spiel *spiel = m0_halon_interface_spiel(hc->hc_hi);
	int rc = 0;

	M0_ENTRY();

	if (!hc->hc_alive) {
		M0_LOG(M0_WARN, "Cannot make SPIEL API call as HAX Python"
				" context has been already destructed");
		return M0_ERR(-ESHUTDOWN);
	}

	if (!hc->hc_rconfc_initialized) {
		M0_LOG(M0_WARN, "Cannot make SPIEL API call as libmotr 'rconfc'"
				" susbsystem hasn't been initialised");
		return M0_ERR(-EDESTADDRREQ);
	}
{code}

It requires rconfc to be already initialized. But according to the current implementation, rconfc is initialized and destructed continually in fs-stats-updater thread. That doesn't look sane.

**Comment by cortx-admin** [comment]
> Vaibhav Prakash Paratwar commented in Jira Server:

[~720599] - is this still relevant? if yes, can we take it in upcoming sprints? cc [~520513]

**Comment by cortx-admin** [comment]
> Justin Woo commented in Jira Server:

[~534380] was this scheduled in the backlog? If so when was it scheduled to be worked on?

**Comment by cortx-admin** [comment]
> Vaibhav Prakash Paratwar commented in Jira Server:

Improvement / Refactor (Design) cc [~520513]

**Comment by cortx-admin** [comment]
> Vaibhav Prakash Paratwar commented in Jira Server:

Moved this to Story JIRA instead of Bug JIRA. cc [~520513] [~520478]

**Comment by shailesh-vaidya** [comment]
Closing as an obsolete
