### ISSUE TITLE
setup_hare script should be integrated with hax source code

### ISSUE THREAD

**Issue by knekrasov** [Seagate/cortx-hare#1464]
The way how this application is written, allows only one way how to use it. It is always a CLI and every nested function can potentially terminate the whole application.

What can be improved:
1. Separate CLI logic from "business logic". Example: pcswrap application: https://github.com/knekrasov/cortx-ha/blob/main/ha/pcswrap/pcswrap/client.py#L387 The business logic can be invoked as pure python, which made it possible to write automatic tests with mocks. 
2. The CLI script itself can be fully generated. So all that we need is to write a valid Python package, write setup.py and declare which function from our script we want to expose via CLI. We use this approach in https://github.com/Seagate/cortx-hare/blob/main/hax/setup.py (`q` and `hax` executables are generated, we don't store them in the source folder). More info on this approach: https://python-packaging.readthedocs.io/en/latest/command-line-scripts.html#the-console-scripts-entry-point

This may be an over-engineering overkill though.

Why it can be helpful:
1. If we see that this script will become ever bigger and more complicated (so it would be nice to move some logic to other Python files and import them for readability).
2. If we see that there is something we can cover with automatic tests. In case of pcswrap it had perfect sense, its logic is quite complicated. 

_Originally posted by @knekrasov in https://github.com/Seagate/cortx-hare/pull/1462#discussion_r561938824_

## Solution
1. Refactor hare_setup in that way so its code becomes a valid module within hax
2. `hare_setup` CLI must be generated from hax/setup.py as described above

**Comment by knekrasov** [comment]
@mssawant @SwapnilGaonkar7 I created this ticket just for the future. I don't think it is of high priority now.

**Comment by justinzw** [comment]
@knekrasov would it be appropriate to close this issue since there is no work scheduled on this issue?

**Comment by knekrasov** [comment]
I'm afraid that this work will be forgotten if we close the issue.

**Comment by cortx-admin** [comment]
> Vaibhav Prakash Paratwar commented in Jira Server:

Improvement ticket cc [~520513]

**Comment by cortx-admin** [comment]
> Vaibhav Prakash Paratwar commented in Jira Server:

Moved this to a story JIRA instead of Bug JIRA as this is improvement task. cc [~520513] [~520478]

**Comment by shailesh-vaidya** [comment]
Closing as an obsolete
