### ISSUE TITLE
hctl shutdown --force

### ISSUE THREAD

**Issue by nezzzu** [Seagate/cortx-hare#1466]
The hctl shutdown command takes a long time to shutdown all the services properly. It is not at all helpful to troubleshoot the cluster. What is desirable is a --force option so that
```
hctl shutdown --force
```
can be used for re-bootstraping a cluster. This option can be disabled in the final release version to prevent accidental data losses.

**Comment by justinzw** [comment]
@mssawant would it be appropriate to close this issue since no work has been done on it for sometime?

**Comment by vaibhavparatwar** [comment]
@nezzzu do you think we can close this issue? Hare team may not be able to schedule in any time soon and with containerized CORTX, we may not need it any more. cc @SunilSavanurSeagate @mssawant

**Comment by cortx-admin** [comment]
> Vaibhav Prakash Paratwar commented in Jira Server:

[~519680] - Can we close this ticket? Commented on respective Github issue. cc [~520513] [~520478]

**Comment by cortx-admin** [comment]
> ganesan umanesan commented in Jira Server:

[~534380] has this been implemented? We wanted this feature a long time ago, I am not sure if this is implemented.

**Comment by cortx-admin** [comment]
> Vaibhav Prakash Paratwar commented in Jira Server:

[~519680] No this is not implemented and right now we do not see any plan in near future to implement this. cc [~520513] [~520478]

**Comment by cortx-admin** [comment]
> ganesan umanesan commented in Jira Server:

[~534380], in that case, please do NOT close and mark as resolved as we will loose important information. Same goes for other unfixed/unresolved EU R&D tickets.

**Comment by cortx-admin** [comment]
> Vaibhav Prakash Paratwar commented in Jira Server:

Improvment cc [~520513]

**Comment by cortx-admin** [comment]
> Vaibhav Prakash Paratwar commented in Jira Server:

Moving this to story JIRA instead of Bug JIRA as this is new request. cc [~520513] [~520478]

**Comment by shailesh-vaidya** [comment]
Closing as an obsolete
