### ISSUE TITLE
/dev/null devices in hctl status output are confusing

### ISSUE THREAD

**Issue by andriytk** [Seagate/cortx-hare#1470]
```
Devices:
    dan-cortx-2.local
    [M0_NC_UNKNOWN]  /dev/sda1
    [M0_NC_UNKNOWN]  /dev/null
    dan-cortx-1.local
    [M0_NC_UNKNOWN]  /dev/null
    [M0_NC_UNKNOWN]  /dev/sda1
    dan-cortx-3.local
    [M0_NC_UNKNOWN]  /dev/sda1
    [M0_NC_UNKNOWN]  /dev/null
```
Source - https://cortxcommunity.slack.com/archives/C019S0SGWNQ/p1611594731028900?thread_ts=1611594582.028700&cid=C019S0SGWNQ

Follow up discussion - https://cortxcommunity.slack.com/archives/C01952XCLCF/p1611596097013800

**Comment by knekrasov** [comment]
@andriytk, @mssawant 

A few questions
1. Do I understand correctly that `/dev/null` should not be shown in hctl status output?
   - So we don't remove `/dev/null` from cfgen because it may be needed for Motr configuration.
2. If so, what should it print instead?

**Comment by andriytk** [comment]
It seems - there is no point in printing dev-nulls at all.

**Comment by mssawant** [comment]
@knekrasov, I think by default we are adding /dev/null CAS device if metadata device is not specified in CDF. Probably we need to make the CAS device mandatory if it is required by Motr or skip configuring a CAS device if not specified.

**Comment by justinzw** [comment]
@mssawant Is there someone appropriate I can assign this issue to?

**Comment by vaibhavparatwar** [comment]
@andriytk Is this issue about "status we show for /dev/null in hctl status when metadata devices are not specified in cdf file" or "we should not show /dev/null in hctl status " ? cc @mssawant  @SunilSavanurSeagate

**Comment by vaibhavparatwar** [comment]
This is currently as per design to show /dev/null when metadata device is not specified in cdf.yaml file 



nodes:
  - hostname: ssc-vm-g2-rhev4-1947.colo.seagate.com
    data_iface: eth1
    data_iface_type: tcp
    transport_type: libfab
    m0_servers:
      - runs_confd: true
        io_disks:
          data: []
      - io_disks:
          data:
            - path: /dev/loop0
            - path: /dev/loop1
            - path: /dev/loop2
            - path: /dev/loop3
      - io_disks:
          data:
            - path: /dev/loop4
            - path: /dev/loop5
            - path: /dev/loop6
            - path: /dev/loop7
    m0_clients:
      - name: m0_client_other  # name of the motr client
        instances: 2   # Number of instances, this host will run
pools:
  - name: the pool
    disk_refs:
      - { path: /dev/loop0, node: ssc-vm-g2-rhev4-1947.colo.seagate.com }
      - { path: /dev/loop1, node: ssc-vm-g2-rhev4-1947.colo.seagate.com }
      - { path: /dev/loop2, node: ssc-vm-g2-rhev4-1947.colo.seagate.com }
      - { path: /dev/loop3, node: ssc-vm-g2-rhev4-1947.colo.seagate.com }
      - { path: /dev/loop4, node: ssc-vm-g2-rhev4-1947.colo.seagate.com }
      - { path: /dev/loop5, node: ssc-vm-g2-rhev4-1947.colo.seagate.com }
      - { path: /dev/loop6, node: ssc-vm-g2-rhev4-1947.colo.seagate.com }
      - { path: /dev/loop7, node: ssc-vm-g2-rhev4-1947.colo.seagate.com }
    #type: sns  # optional; supported values: "sns" (default), "dix", "md"
    data_units: 1
    parity_units: 0
    #allowed_failures: { site: 0, rack: 0, encl: 0, ctrl: 0, disk: 0 }
Hctl status:

Text
[root@ssc-vm-g2-rhev4-1947 hare]# hctl status -d
Bytecount:
    critical : 0
    damaged : 0
    degraded : 0
    healthy : 0
Data pool:
    # fid name
    0x6f00000000000001:0x39 'the pool'
Profile:
    # fid name: pool(s)
    0x7000000000000001:0x5a 'default': 'the pool' None None
Services:
    ssc-vm-g2-rhev4-1947.colo.seagate.com  (RC)
    [started]  hax                 0x7200000000000001:0x7          inet:tcp:192.168.62.178@22001
    [started]  confd               0x7200000000000001:0xa          inet:tcp:192.168.62.178@21001
    [started]  ioservice           0x7200000000000001:0xd          inet:tcp:192.168.62.178@21002
    [started]  ioservice           0x7200000000000001:0x1e         inet:tcp:192.168.62.178@21003
    [unknown]  m0_client_other     0x7200000000000001:0x2f         inet:tcp:192.168.62.178@21501
    [unknown]  m0_client_other     0x7200000000000001:0x32         inet:tcp:192.168.62.178@21502
Devices:
    ssc-vm-g2-rhev4-1947.colo.seagate.com
    [online]  /dev/loop4
    [online]  /dev/loop5
    [online]  /dev/loop6
    [online]  /dev/loop7
    [online]  /dev/null
    [online]  /dev/null
    [online]  /dev/loop0
    [online]  /dev/loop1
    [online]  /dev/loop2
    [online]  /dev/loop3

**Comment by cortx-admin** [comment]
> Vaibhav Prakash Paratwar commented in Jira Server:

Improvement / Refactoring (Design) cc [~520513]

**Comment by shailesh-vaidya** [comment]
Closing as an obsolete
