### ISSUE TITLE
Problem: CDF generation in scope of Mini Provisioner is incompete

### ISSUE THREAD

**Issue by knekrasov** [Seagate/cortx-hare#1477]
In scope of #1467 CDF generation was implemented. The implementation is sufficient for singlenode but in the future the following issues must be addressed:

1. Number of S3 instances is not taken from ConfStore. Now it is hard-coded to 11.
2. Metadata storage is always taken as `store.get(f'cluster>{name}>storage>metadata_devices')[0]`. Situation when list of metadata devices is empty will break the code.
3. Data interface type is now hardcoded to "tcp". ConfStore value `cluster>{server-node}>network>data>interface_type` is not considered.

**Comment by knekrasov** [comment]
Point \[3] is resolved in scope of #1494.
So the only problem left is \[2]: Metadata storage is always taken as `store.get(f'cluster>{name}>storage>metadata_devices')[0]`.

**Comment by knekrasov** [comment]
Related JIRA ticket:
[EOS-17160](https://jts.seagate.com/browse/EOS-17160) cfgen expects a single meta data device instead of a list

**Comment by vaibhavparatwar** [comment]
We have JIRA story ticket to track #2 from the issue mentioned. Other two are addressed already.

**Comment by cortx-admin** [comment]
> Vaibhav Prakash Paratwar commented in Jira Server:

For #1 - We now do not hardcode number of instances for S3 (or rgw now). So this is taken care.
For #2 - We are tracking it in separate JIRA CORTX-17160
For #3 - We have recently implemented to take interface type from confstore key value. 
               we read it from below key. 

# Expected format '<protocol>://<hostname>:<port>'
# e.g. endpoints:
# - tcp://data1-node1:22001 # For motr and Hax communication
# - tcp://data1-node2:22001 # For motr and Hax communication

**Comment by cortx-admin** [comment]
> Vaibhav Prakash Paratwar commented in Jira Server:

.

**Comment by cortx-admin** [comment]
> Vaibhav Prakash Paratwar commented in Jira Server:

.

**Comment by cortx-admin** [comment]
> Vaibhav Prakash Paratwar commented in Jira Server:

..

**Comment by cortx-admin** [comment]
> Vaibhav Prakash Paratwar commented in Jira Server:

.
