### ISSUE TITLE
hctl bootstrap does not show on which node is the problem with /var/lib/hare permissions

### ISSUE THREAD

**Issue by andriytk** [Seagate/cortx-hare#1486]
```
[seagate@sage-tier1-1 ~]$ hctl bootstrap --mkfs /home/users/project/SHARED/sage-update-20201028/sage-proto-cdf.yaml
2021-02-03 11:08:47: Generating cluster configuration...bash: /var/lib/hare/node-name: Permission denied
```
It's quite inconvenient.

**Comment by Shreya-18** [comment]
Jira Ticket : https://jts.seagate.com/browse/EOS-18914

**Comment by vaibhavparatwar** [comment]
Looks like this issue is resolved as per JIRA updates. Closing it. If it is seen again, please open a new issue.

**Comment by cortx-admin** [comment]
> Vaibhav Prakash Paratwar commented in Jira Server:

Duplicate

**Comment by cortx-admin** [comment]
> Vaibhav Prakash Paratwar commented in Jira Server:

.

**Comment by cortx-admin** [comment]
> Vaibhav Prakash Paratwar commented in Jira Server:

.
