### ISSUE TITLE
[Mini Provisioner] hare_setup fails to run with 'hare_mp' ModuleNotFoundError

### ISSUE THREAD

**Issue by parikshit-dharmale** [Seagate/cortx-hare#1499]
After doing git clone and make install of hare repo, running hare_setup script from terminal gives error as ModuleNotFoundError:: No module named 'hare_mp'

O/P:
```
[ cortx-hare]#  /opt/seagate/cortx/hare/bin/hare_setup --help
Traceback (most recent call last):
  File "/opt/seagate/cortx/hare/bin/hare_setup", line 7, in <module>
    from hare_mp.main import main
ModuleNotFoundError: No module named 'hare_mp'
```

**Comment by hessio** [comment]
Hi @parikshit-dharmale I am looking into reproducing this error for you now. I am currently trying to reproduce your error now. I will get back to you shortly.

**Comment by supritshinde** [comment]
Resolved the issue. PR for ref: https://github.com/Seagate/cortx-hare/pull/1538
