### ISSUE TITLE
utils/utils.py must be integrated into hax module

### ISSUE THREAD

**Issue by knekrasov** [Seagate/cortx-hare#1502]
utils/utils.py is a result of hare-shutdown script refactoring. In fact it reuses some of the types from hax already (like `HAConsistencyException` but still re-implements some other things that are already invented in hax code base. For instance, all communication with consul happens directly via `python-consul` 's Consul class. So in case of intermittent Consul exceptions retry will not happen.

Consequent evolution of this module will most probably cause code duplication and will double bugs. We need to incorporate this code into the existing solid code base.

**Comment by knekrasov** [comment]
Mirror JIRA ticket created https://jts.seagate.com/browse/EOS-18799

**Comment by cortx-admin** [comment]
> Vaibhav Prakash Paratwar commented in Jira Server:

Improvement cc [~520513]

**Comment by vaibhavparatwar** [comment]
This will be handled separately as design changing. Closing this as of now @mssawant

**Comment by cortx-admin** [comment]
> Vaibhav Prakash Paratwar commented in Jira Server:

.

**Comment by cortx-admin** [comment]
> Vaibhav Prakash Paratwar commented in Jira Server:

.

**Comment by cortx-admin** [comment]
> Vaibhav Prakash Paratwar commented in Jira Server:

.
