### ISSUE TITLE
Failing grep command in /opt/seagate/cortx/hare/libexec/m0crate-io-conf > /tmp/m0crate-io.yaml.

### ISSUE THREAD

**Issue by somnathbghule** [Seagate/cortx-hare#1506]
While running IO test using m0crate utility, grep command is failing /opt/seagate/cortx/hare/libexec/m0crate-io-conf >/tmp/m0crate-io.yaml step.

Identical error message present in https://github.com/Seagate/cortx-hare/issues/1391 issue at the bottom.

[root ~]# /opt/seagate/cortx/hare/libexec/m0crate-io-conf >/tmp/m0crate-io.yaml
Usage: grep [OPTION]... PATTERN [FILE]...
Try 'grep --help' for more information.
Usage: grep [OPTION]... PATTERN [FILE]...
Try 'grep --help' for more information.

**Comment by vaibhavparatwar** [comment]
@somnathbghule You can ignore those "Usage: grep" messages if resulting yaml file in /tmp folder is created.
We are tracking this as a minor bug as its not breaking functionality.

**Comment by vaibhavparatwar** [comment]
Not getting this error now: 
[root@ssc-vm-g2-rhev4-1947 ~]# /opt/seagate/cortx/hare/libexec/m0crate-io-conf
CrateConfig_Sections: [MOTR_CONFIG, WORKLOAD_SPEC]
MOTR_CONFIG:
   MOTR_LOCAL_ADDR: inet:tcp:10.230.240.185@21501
   MOTR_HA_ADDR:    inet:tcp:10.230.240.185@22001
   PROF: <0x7000000000000001:0x4e>  # Profile fid
   LAYOUT_ID: 9                      # Defines the UNIT_SIZE (9: 1MB)
   IS_OOSTORE: 1                     # Is oostore-mode?
   IS_READ_VERIFY: 0                 # Enable read-verify?
   TM_RECV_QUEUE_MIN_LEN: 16  # Minimum length of the receive queue
   MAX_RPC_MSG_SIZE: 65536    # Maximum rpc message size
   PROCESS_FID: <0x7200000000000001:0x27>
   IDX_SERVICE_ID: 1
LOG_LEVEL: 4  # err(0), warn(1), info(2), trace(3), debug(4)
WORKLOAD_SPEC:                # Workload specification section
   WORKLOAD:                  # First Workload
      WORKLOAD_TYPE: 1        # Index(0), IO(1)
      WORKLOAD_SEED: tstamp   # SEED to the random number generator
      OPCODE: 3               # Operation(s) to test: 2-WRITE, 3-WRITE+READ
      IOSIZE: 10m      # Total Size of IO to perform per object
      BLOCK_SIZE: 2m          # In N+K conf set to (N * UNIT_SIZE) for max perf
      BLOCKS_PER_OP: 1        # Number of blocks per motr operation
      MAX_NR_OPS: 1           # Max concurrent operations per thread
      NR_OBJS: 10             # Number of objects to create by each thread
      NR_THREADS: 4           # Number of threads to run in this workload
      RAND_IO: 1              # Random (1) or sequential (0) IO?
      MODE: 1                 # Synchronous=0, Asynchronous=1
      THREAD_OPS: 0           # All threads write to the same object?
      NR_ROUNDS: 1            # Number of times this workload is run
      EXEC_TIME: unlimited    # Execution time (secs or "unlimited")
      SOURCE_FILE: /tmp/128M  # Source data file

Closing this ticket

**Comment by cortx-admin** [comment]
> Vaibhav Prakash Paratwar commented in Jira Server:

Now we are not getting this error.. 
[root@ssc-vm-g2-rhev4-1947 ~]# /opt/seagate/cortx/hare/libexec/m0crate-io-conf
CrateConfig_Sections: [MOTR_CONFIG, WORKLOAD_SPEC]
MOTR_CONFIG:
   MOTR_LOCAL_ADDR: inet:tcp:10.230.240.185@21501
   MOTR_HA_ADDR:    inet:tcp:10.230.240.185@22001
   PROF: <0x7000000000000001:0x4e>  # Profile fid
   LAYOUT_ID: 9                      # Defines the UNIT_SIZE (9: 1MB)
   IS_OOSTORE: 1                     # Is oostore-mode?
   IS_READ_VERIFY: 0                 # Enable read-verify?
   TM_RECV_QUEUE_MIN_LEN: 16  # Minimum length of the receive queue
   MAX_RPC_MSG_SIZE: 65536    # Maximum rpc message size
   PROCESS_FID: <0x7200000000000001:0x27>
   IDX_SERVICE_ID: 1
LOG_LEVEL: 4  # err(0), warn(1), info(2), trace(3), debug(4)
WORKLOAD_SPEC:                # Workload specification section
   WORKLOAD:                  # First Workload
      WORKLOAD_TYPE: 1        # Index(0), IO(1)
      WORKLOAD_SEED: tstamp   # SEED to the random number generator
      OPCODE: 3               # Operation(s) to test: 2-WRITE, 3-WRITE+READ
      IOSIZE: 10m      # Total Size of IO to perform per object
      BLOCK_SIZE: 2m          # In N+K conf set to (N * UNIT_SIZE) for max perf
      BLOCKS_PER_OP: 1        # Number of blocks per motr operation
      MAX_NR_OPS: 1           # Max concurrent operations per thread
      NR_OBJS: 10             # Number of objects to create by each thread
      NR_THREADS: 4           # Number of threads to run in this workload
      RAND_IO: 1              # Random (1) or sequential (0) IO?
      MODE: 1                 # Synchronous=0, Asynchronous=1
      THREAD_OPS: 0           # All threads write to the same object?
      NR_ROUNDS: 1            # Number of times this workload is run
      EXEC_TIME: unlimited    # Execution time (secs or "unlimited")
      SOURCE_FILE: /tmp/128M  # Source data file

**Comment by cortx-admin** [comment]
> Vaibhav Prakash Paratwar commented in Jira Server:

Not reproducing now

**Comment by cortx-admin** [comment]
> Vaibhav Prakash Paratwar commented in Jira Server:

.

**Comment by cortx-admin** [comment]
> Vaibhav Prakash Paratwar commented in Jira Server:

.

**Comment by cortx-admin** [comment]
> Vaibhav Prakash Paratwar commented in Jira Server:

.
