### ISSUE TITLE
Problem: Hare does not detect deadlock in a monitored Motr process

### ISSUE THREAD

**Issue by andriytk** [Seagate/cortx-hare#1516]
Currently, Hare only knows whether the Motr process is running or not, but it does not know whether it can respond to the fops queries. So in case there is a deadlock inside Motr process - Hare wouldn't know about it and would still show the process status as "started" in `hctl status`.

Suggestion: `hax` to send periodic ping/keepalive fops to each local Motr process to check it.

**Comment by knekrasov** [comment]
@andriytk 
1. If some motr process doesn't reply to ping - what hax should do next?
2. Can you point to an example how to send such a ping/keepalive fop? I would be happy to help with this issue but I'm quite ignorant of Motr API specifics.

**Comment by andriytk** [comment]
1) Send FAILED ha-status for it. Similar to the case when the whole process dies.
2) Check `m0_ha_msg_keepalive_req` at `motr/keepalive.h`. Ask @max-seagate also.

**Comment by knekrasov** [comment]
Created mirror JIRA issue: https://jts.seagate.com/browse/EOS-18469
Hopefully it will speed the things up.

**Comment by hessio** [comment]
Is this issue still relevant?

**Comment by cortx-admin** [comment]
> Vaibhav Prakash Paratwar commented in Jira Server:

[~520478] can you please help in understanding if this is still relevant?

**Comment by shailesh-vaidya** [comment]
Closing as an obsolete
