### ISSUE TITLE
Refactoring of hare-bootstrap and hare-node-join scripts (common functions)

### ISSUE THREAD

**Issue by Shreya-18** [Seagate/cortx-hare#1519]
The common functions are present in script `hare-utils`. Refactor `hare-bootstrap` and `hare-node-join` scripts to make use of such functions from `hare-utils`. 
For example `wait4()` is duplicated in all scripts.

**Comment by knekrasov** [comment]
This is just a code polishing, no changes for the end user are expected to appear in scope of this issue.

**Comment by Shreya-18** [comment]
Jira ticket : https://jts.seagate.com/browse/EOS-18916

**Comment by cortx-admin** [comment]
> Vaibhav Prakash Paratwar commented in Jira Server:

Already taken as a story task

**Comment by cortx-admin** [comment]
> Vaibhav Prakash Paratwar commented in Jira Server:

Duplicated.

**Comment by vaibhavparatwar** [comment]
Closing this as we have Story ticket to take care of this if at all required.

**Comment by cortx-admin** [comment]
> Vaibhav Prakash Paratwar commented in Jira Server:

Duplicate so cloing this. tracking in other story

**Comment by cortx-admin** [comment]
> Vaibhav Prakash Paratwar commented in Jira Server:

.

**Comment by cortx-admin** [comment]
> Vaibhav Prakash Paratwar commented in Jira Server:

.
