### ISSUE TITLE
hctl status and hctl shutdown ModuleNotFoundError: No module named 'hax'

### ISSUE THREAD

**Issue by yanqingfu** [Seagate/cortx-hare#1544]
[root@ssc-vm-2736 hare]# hctl status
Traceback (most recent call last):
  File "/opt/seagate/cortx/hare/libexec/hare-status", line 32, in <module>
    from hax.exception import HAConsistencyException
**ModuleNotFoundError: No module named 'hax'**

[root@ssc-vm-2736 hare]# hctl shutdown
Traceback (most recent call last):
  File "/opt/seagate/cortx/hare/libexec/hare-shutdown", line 28, in <module>
    from hax.util import ConsulUtil, repeat_if_fails
**ModuleNotFoundError: No module named 'hax'**

**Comment by knekrasov** [comment]
@yanqingfu what version of hare do you use?

I guess this issue has been already fixed in the latest main branch.

**Comment by yanqingfu** [comment]
@knekrasov how to check the version of hare?
I use `git clone https://github.com/Seagate/cortx-hare.git hare`  today to get the hare, this should get the latest version of hare

**Comment by knekrasov** [comment]
@yanqingfu that's correct, it would be the latest version for sure. 
Can you try the following:
1. go to cortx-hare/ folder (the one where you cloned the sources to)
2. sudo make uninstall
3. git clean -dfx
4. And then try to reproduce the issue?

How did you install hare BTW? Was it `make devinstall` or `make install`? Has the command succeed?

**Comment by yanqingfu** [comment]
Hi @knekrasov seems that we need to change the doc https://github.com/Seagate/cortx-hare/blob/main/README.md

with `make install` hctl works while 'make devinstall' hctl not working. In the doc, it indicates 'make devinstall'

[haxerrorwithmakedevinstal.txt](https://github.com/Seagate/cortx-hare/files/6147995/haxerrorwithmakedevinstal.txt)

**Comment by knekrasov** [comment]
Hm, it seems like you're right. As a workaround, I can suggest two approaches (either ones):
1. use `make install` instead of devinstall
2. after `make devinstall` is invoked, activate the virtualenv with the command like this `source <your-hare-folder>/.py3venv/bin/activate`

**Comment by yanqingfu** [comment]
resolved
