### ISSUE TITLE
[README of HARE] : For the step of installing MOTR using RPM, need to add steps in case of failure

### ISSUE THREAD

**Issue by vaibhavparatwar** [Seagate/cortx-hare#1589]
While installing MOTR using RPMs I faced follwing issue: 

[root@ssc-vm-3353 hare]# sudo yum -y install cortx-motr cortx-motr-devel
Loaded plugins: fastestmirror, product-id, search-disabled-repos, subscription-manager
Loading mirror speeds from cached hostfile
EOS_CentOS-7_CentOS-7-Extras                                                                                                                                          | 2.1 kB  00:00:00
EOS_CentOS-7_CentOS-7-OS                                                                                                                                              | 2.1 kB  00:00:00
EOS_CentOS-7_CentOS-7-Updates                                                                                                                                         | 2.1 kB  00:00:00
EOS_EPEL-7_EPEL-7                                                                                                                                                     | 2.5 kB  00:00:00
EOS_Puppet6_puppet6-el7                                                                                                                                               | 2.1 kB  00:00:00
No package cortx-motr available.
No package cortx-motr-devel available.
Error: Nothing to do

For resolving this I had to add last successful repo (which are internal and not yet available for community) first using following commands. So we can add these commands as notes in the section if someone faces the issue mentioned above, they can  run following commands and get it resolved. 

Here is the section :
https://github.com/Seagate/cortx-hare#building-from-source

**Comment by TechWriter-Mayur** [comment]
Hi @vaibhavparatwar! 

Thank you so much for your contribution.

We can add this information as an additional information in the document in case someone face the similar issue. But the associated links only works in the Seagate environment (Internal Seagate folks) and our open-source community cannot use this link. Please share the GitHub links for the same with us.

**Comment by vaibhavparatwar** [comment]
@TechWriter-Mayur thanks for response. I am not aware about GitHub link for the same (cortx-motr repos). @cortx-admin - could you please help here?

**Comment by TechWriter-Mayur** [comment]
@mukul-seagate11 : We cannot use these internal links in the document for community, we need to find some other way to add these rpm to GitHub then we can add it to HARE User Guide.

**Comment by mukul-seagate11** [comment]
@s-arya, please address the issue as reported

**Comment by knekrasov** [comment]
@mukul-seagate11 What solution would you suggest as an architect?

**Comment by mukul-seagate11** [comment]
@knekrasov, as this has been routed to the hare gatekeepers so they have to figure out & discussion internal to resolve the issue?

**Comment by knekrasov** [comment]
@mukul-seagate11 Hare gatekeepers know how to keep the source code clean and working. But the strategy how the whole product goes open source, what user experience external users will get while working with Seagate repositories, make sure that the strategy is kept consistent throughout all components - that is definitely out of our responsibility.

That being said, I can suggest just removing the RPMs from the document and force the users to build everything by themselves but that's only because that's my normal workflow. But that's definitely not an informed decision. Decisions (especially strategic ones) should be made by the people with the corresponding background. So please advise.
