### ISSUE TITLE
make command fails when installing HARE on VM

### ISSUE THREAD

**Issue by hessio** [Seagate/cortx-hare#1597]
When I run `make` command in the HARE setup guide I get this error: 

```
hare_mp/store.py:21: error: Cannot find implementation or library stub for module named 'cortx.utils.conf_store'
hare_mp/main.py:34: error: Cannot find implementation or library stub for module named 'cortx.utils.product_features'
hare_mp/main.py:34: note: See https://mypy.readthedocs.io/en/latest/running_mypy.html#missing-imports
Found 2 errors in 2 files (checked 8 source files)
make[2]: *** [mypy] Error 1
make[1]: *** [check-miniprov] Error 2
make: *** [build] Error 2
```

Tagging @mukul-seagate11 for some extra support as to where to resolve this issue.

**Comment by knekrasov** [comment]
Please make sure that you have cortx-py-utils installed. Unfortunately, our README file doesn't express that dependency but we have PR for that already: #1595

**Comment by supritshinde** [comment]
Installation of Cortx utils would solve the issue. @hessio

**Comment by hessio** [comment]
Once I installed cortx-py-utils issue was resolved.
