### ISSUE TITLE
Information required for Hare QSG

### ISSUE THREAD

**Issue by Saumya-Sunder** [Seagate/cortx-hare#1636]
Hi,
We need the following information to make the Hare Quickstart Guide more accurate and Community friendly.

- Missing the standard configuration information including RAM, Processor, Storage, NICs, etc.

- Prerequisites to install required components including git, and other components.

**Comment by TechWriter-Mayur** [comment]
@mukul-seagate11 If possible, could you please assign this to an appropriate person. I think the minimum requirements should be same as CORTX OVA installation but we need to check with respective SMEs.

**Comment by mukul-seagate11** [comment]
@suvratjoshi, please check

**Comment by suvratjoshi** [comment]
Hello @Saumya-Sunder,
I am trying to understand this requirement well.
We have [this README file](https://github.com/Seagate/cortx-hare/#readme) which acts as a quick setup / start guide for Hare.
And we have [1-node](https://github.com/Seagate/cortx-hare/wiki/Hare-provisioning-for-single-node-deployment) and [3-node](https://github.com/Seagate/cortx-hare/wiki/Hare-provisioning-for-3-node-deployment) deployment guides present in [Hare - wiki](https://github.com/Seagate/cortx-hare/wiki/).

So on which page do we need updates exactly? or are you planning to create a separate QSG page?
Some more details regarding this would be nice to have.

```
Missing the standard configuration information including RAM, Processor, Storage, NICs, etc.
```
-> If we already have some reference link from other other components/template/format, please mention. so we can do it similarly.

```
Prerequisites to install required components including git, and other components.
```
-> Wiki already covers most of the things (but not git installation probably). Any references if exist, would be helpful here too.

Thanks!
cc: @vaibhavparatwar @NeeravChoudhari

**Comment by TechWriter-Mayur** [comment]
@suvratjoshi, We are trying to enhance the document readability. So these are the basic requirement that the user wants to know if a community user wants to build a CORTX HARE set-up.  On the HARE QSG, we are not specifying any of the requirements. We are looking for a basic requirement like, which OS and its version CORTX Supports, what are memory, storage, and processor requirements CORTX has. Does internet connectivity require? if yes, how many network interfaces required? these are basic queries we are trying to resolve by gathering this information.

As our single guide has both one-node and three-node instructions, we need to provide this information for both types of setup. 

@Saumya-Sunder please correct or add if anything else required.

**Comment by suvratjoshi** [comment]
@TechWriter-Mayur,
The requirement says `Information required for Hare QSG`
`We need the following information to make the Hare Quickstart Guide more accurate and Community friendly.`
But from your reply, it looks that, this is not Hare component specific ask, but the requirements for Cortx software. 

Let me try to explain : 
`So these are the basic requirement that the user wants to know if a community user wants to build a CORTX HARE set-up.`
--> Hare component is not a standalone software, but it is one of the components of Cortx software with multiple component layers (full stack). It is not having component specific hardware requirements as such. It will be used on the same hardware / VM where full stack is deployed. So, same pre-requisites are applicable to Hare (or I think any other component), which we are mentioning for Cortx software. So I dont think we need to specify any hardware requirements under Hare section.
Hare component deployment specific requirements are already mentioned on the pages that I already pointed out.
If something specific to Hare component (and not common to Cortx), is missing from the pages that I pointed, we can provide that information for sure.

`We are looking for a basic requirement like, which OS and its version CORTX Supports, what are memory, storage, and processor requirements CORTX has. Does internet connectivity require? if yes, how many network interfaces required? these are basic queries we are trying to resolve by gathering this information.`
--> Hi @NeeravChoudhari , @ujjwalpl ,
Can you please point to an appropriate - document which or a person who - can provide this required information for Cortx software Quick Start Guide (QSG).

Thank you!
cc: @vaibhavparatwar , @mssawant

**Comment by Saumya-Sunder** [comment]
@suvratjoshi for a stat, could you look at the OVA document and let me know if the config is good to go with? If anything is missing, please let me know. Please also let us know what are the dependencies in terms of installs and components by reading the current Hare guide. Would that help?

**Comment by vaibhavparatwar** [comment]
@Saumya-Sunder please refer this document for configuration required for VMs if you are doing release build creation.
https://github.com/Seagate/cortx/blob/main/doc/Release_Build_Creation.rst#prerequisites-to-setup-virtual-machine

For OVA this is the link 
https://github.com/Seagate/cortx/blob/main/doc/CORTX_on_Open_Virtual_Appliance.rst#cortx-on-open-virtual-appliance

cc @NeeravChoudhari  @ujjwalpl @suvratjoshi

**Comment by Saumya-Sunder** [comment]
Hey @vaibhavparatwar @NeeravChoudhari @ujjwalpl @suvratjoshi I hope this would make better sense: 
https://github.com/Seagate/cortx-management-portal/blob/main/docs/CortxManagementPortalQuickstart.md

This is how I want to structure the QSG. If this does not clarify your doubts, then let's get on a call?

**Comment by Saumya-Sunder** [comment]
Hey @vaibhavparatwar, thanks for giving me the input today. As per our discussion, I will update the guide and update you on the same.

**Comment by vaibhavparatwar** [comment]
@Saumya-Sunder can we close this ticket now?

**Comment by Saumya-Sunder** [comment]
Yes, thanks for setting up the time to resolve this.
