### ISSUE TITLE
Unable to copy singlenode.yaml while preparing CDF

### ISSUE THREAD

**Issue by TechWriter-Mayur** [Seagate/cortx-hare#1640]
I am not able copy the singlenode.yaml using the `cp /opt/seagate/cortx/hare/share/cfgen/examples/singlenode.yaml ~/CDF.yaml` command. See the error image:

![image](https://user-images.githubusercontent.com/64980335/121335883-a051d080-c938-11eb-98bb-cac2c439c00f.png)

I am following [HARE QSG](https://github.com/Seagate/cortx-hare#prepare-the-cdf).

**Comment by hessio** [comment]
Have you seen any errors before this?

**Comment by knekrasov** [comment]
@TechWriter-Mayur Have you installed hare rpm before trying to copy the file?
Or maybe you've built it manually from the sources (using `make install`)?

**Comment by TechWriter-Mayur** [comment]
@knekrasov Yes, I have installed the RPM using `sudo make install` as suggested: https://github.com/Seagate/cortx-hare#building-from-source.

**Comment by hessio** [comment]
Have you installed py-utils?

**Comment by TechWriter-Mayur** [comment]
> Have you installed py-utils?

No, the information is not there in the QSG but I have installed `python3 python3-devel`.

**Comment by knekrasov** [comment]
@TechWriter-Mayur 
> @knekrasov Yes, I have installed the RPM using sudo make install as suggested: https://github.com/Seagate/cortx-hare#building-from-source.

Did the command succeed? 
Does `/opt/seagate/hare/share` folder exist? What is the output of `ls -lh /opt/seagate/cortx/hare/` command?

**Comment by knekrasov** [comment]
@TechWriter-Mayur I believe `make install` didn't actually succeed. Can you re-run it and provide the output here?

**Comment by TechWriter-Mayur** [comment]
> @TechWriter-Mayur I believe `make install` didn't actually succeed. Can you re-run it and provide the output here?

okay, sure. retrying.

**Comment by TechWriter-Mayur** [comment]
Thanks @knekrasov; the solution works. But we need to perform make install in the `hare` directory else it won't work.  The information should be added in the doc. Also, Don't we need to deploy CORTX S3Server for IO operations?

**Comment by shindesuprit1** [comment]
@TechWriter-Mayur make install wouldn’t work if not ran in the hare directory itself. If done elsewhere it won’t execute successfully. And if make install is done properly, you’ll surely find the files.

**Comment by TechWriter-Mayur** [comment]
@shindesuprit1, thank you so much for your valuable suggestion. The cluster is now up and running but still the IO Services are **offline**. See the attached screenshot. Do we need to deploy CORTX S3Server for IO operations?

![image](https://user-images.githubusercontent.com/64980335/121553630-0fa9ec00-ca2f-11eb-8f5a-f4fb3d1c4c46.png)

**Comment by knekrasov** [comment]
@TechWriter-Mayur when ioservice is down, it is definitely not the right situation.
What was the output of your `hctl bootstrap` command?

I guess you saw something similar to #1628 ?

**Comment by TechWriter-Mayur** [comment]
@knekrasov yes, it is same issue.and the same output.

**Comment by shindesuprit1** [comment]
Hi @TechWriter-Mayur I guess this issue was addressed by a patch a day before by Konstantin. Just to know, did you try setting up using latest HARE code? 
NO, cortx s3 servers deployment isn’t needed for ioservice to be up. Also try out stopping the ioservice manually “systemctl stop 0x72.....1: oxc” and then restarting. If not reboot the node once and bootstrap again. But that’s naive and not recommended way actually.

**Comment by knekrasov** [comment]
@TechWriter-Mayur let's get back to the title issue.

I can see you've managed to run `hctl bootstrap`. Does it mean that your title problem is resolved and the command `cp /opt/seagate/cortx/hare/share/cfgen/examples/singlenode.yaml ~/CDF.yaml` now works fine?

**Comment by TechWriter-Mayur** [comment]
@knekrasov yes, this is resolved. I am able to copy the singlenode.yaml file. Also, the cluster is running but the IO services are now in offline status. So I was looking for your assistance on that point.

But, as @shindesuprit1  suggested, I will try to install HARE on fresh set-up as a fix is merged. I will update if, any issue occurs.

**Comment by vaibhavparatwar** [comment]
@TechWriter-Mayur  I am closing title issue now as its working for you.
