### ISSUE TITLE
group 'hare' does not exist

### ISSUE THREAD

**Issue by mengwanguc** [Seagate/cortx-hare#1659]
Hello,

I followed Hare installation instructions. However, after "sudo make install", when I tried to add current user to "hare" group, I got the following output:

```
[cc@motr experiments]$ sudo usermod --append --groups hare $USER
usermod: group 'hare' does not exist
```

Looks like "sudo make install" didn't create "hare" group, but I suppose it should? (just assumption)

Is it a big problem?
(Though I didn't manage to add current user to "hare" group, I can still bootstrap the cluster and perform IO using "m0cp" and "m0cat" [following this guide](https://github.com/Seagate/Cortx/blob/main/doc/Cluster_Setup.md).)

**Comment by hessio** [comment]
Hi @mengwanguc no this is not a big issue, I personally am not sure what this is used for as I have not been able to get this command to complete either. @knekrasov can you help with what this command does, is it necessary?

**Comment by daniarherikurniawan** [comment]
Just a quick note, a few months ago this problem did not occur. Back then, the guideline use `sudo make devinstall` instead of `sudo make install`. 
I am not sure what is the effect of not having the `hare` group, but I believe it is needed for managing the right access so that only users in `hare` group can manage CORTX cluster through hare.

**Comment by daniarherikurniawan** [comment]
After a bit of digging, turns out only `devinstall` has `@groupadd --force hare` which is creating hare group for some reasons. 
Since the current guideline use `make install`, I believe the `sudo usermod --append --groups hare $USER` is **not** needed and should be removed from the docs.

**Comment by mengwanguc** [comment]
> Just a quick note, a few months ago this problem did not occur. Back then, the guideline use `sudo make devinstall` instead of `sudo make install`.
> I am not sure what is the effect of not having the `hare` group, but I believe it is needed for managing the right access so that only users in `hare` group can manage CORTX cluster through hare.

I will get permission issues if I run "m0cp" as current user. But I won't have problem if I run everything as root user.

**Comment by daniarherikurniawan** [comment]
With respect to the Quickstart checklist: `5.  <user> is a member of hare group ..`, perhaps we do need to create the hare group manually, or add `@groupadd --force hare`  on the make file (`make install`). We can create a PR if this is the correct solution.

**Comment by suvratjoshi** [comment]
I think we need to modify page https://github.com/Seagate/cortx-hare/blob/main/README.md and replace `make install` with `make devinstall`.
I think currently this `make install`  instruction is there, as previously there were some issues with `make devinstall` and we were not able to merge the related PR to main branch as it was locked.
Right @knekrasov ?

**Comment by knekrasov** [comment]
@suvratjoshi `make devinstall` is intended to be used by the developers. In this case it is easier to debug as long as the changes get 'deployed' automatically, there is no need to rebuild Hare and reinstall it. I don't think that this is the most-used use case for those who'll read README.md file.

I'm not really sure that `hare` group is really required to run Hare. So probably there is a discrepancy between our checklists and `make install` functionality.

**Comment by daniarherikurniawan** [comment]
@suvratjoshi, @knekrasov, I believe we need to update the Readme to avoid further confusion when the public follows the instructions. I am currently interning under John Bent supervision, and my main task is to find out any possible problem/bug related to all CORTX's readme. 

Let us know the preferable solution, and we can make the PR for it. Thanks

**Comment by vaibhavparatwar** [comment]
@daniarherikurniawan - we are looking in to this. @mssawant will let us know what can be done here.. if change is required in README or we do not need to use this step of creating hare group. Thank you for contributing.

**Comment by vaibhavparatwar** [comment]
PR for this created by @daniarherikurniawan  has been merged in to main README. closing this.
