### ISSUE TITLE
No package cortx-py-utils available

### ISSUE THREAD

**Issue by mengwanguc** [Seagate/cortx-hare#1660]
In the Hare installation instructions, it asks us to install py-utils using `sudo yum -y install cortx-py-utils`.

However, it doesn't work on my side:
```
[cc@s3 cortx-s3server]$ sudo yum -y install cortx-py-utils
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: mirror.teklinks.com
 * epel: pubmirror1.math.uh.edu
 * extras: repo1.dal.innoscale.net
 * updates: mirror.rackspace.com
No package cortx-py-utils available.
Error: Nothing to do
```

Looks like that's not the correct way to install cortx-py-utils.

I think the correct way will be following the instructions here:
https://github.com/Seagate/cortx-utils/blob/main/py-utils/README.md

I can submit a PR to correct this issue. Just let me know.
Thanks

**Comment by hessio** [comment]
Yes I think you are right I will create this PR now, thanks @mengwanguc

**Comment by kiwionly2** [comment]
Also solve for issue #1658

**Comment by vaibhavparatwar** [comment]
Closing this as PR is merged to main.
