### ISSUE TITLE
Is cortx-motr-tests-ut-*.rpm needed?

### ISSUE THREAD

**Issue by daniarherikurniawan** [Seagate/cortx-hare#1664]
I am following the readme to install Hare. The `scripts/m0 make rpms` will generate 5 rpms inside `~/rpmbuild/RPMS/x86_64/`. One of the rpm is `cortx-motr-tests-ut-2.0.0-*.el7.x86_64.rpm` which can't be installed. When we run `sudo rpm -ivh ~/rpmbuild/RPMS/x86_64/cortx-hare-*.rpm`, it will generate this error 
```sh
error: Failed dependencies:
	cortx-motr conflicts with cortx-motr-tests-ut-2.0.0-1_gite28e4d3_3.10.0_1127.19.1.el7.x86_64
```

Which in turn will prevent the installation of the other 4 RPMs. 

So, what is the purpose of this `cortx-motr-tests-ut-2.0.0-*.el7.x86_64.rpm` and can we remove it from the `~/rpmbuild/RPMS/x86_64/` so that the other rpm installation can run without error?

Thanks

**Comment by vaibhavparatwar** [comment]
@pavankrishnat pls make necessary changes in README.

**Comment by pavankrishnat** [comment]
Yes @daniarherikurniawan we can remove `cortx-motr-tests-ut-2.0.0-*.el7.x86_64.rpm` and install other rpms

**Comment by daniarherikurniawan** [comment]
@vaibhavparatwar @pavankrishnat , I made this PR https://github.com/Seagate/cortx-hare/pull/1672 to address this. Feel free to close the PR if you have another solution. Thanks!

**Comment by vaibhavparatwar** [comment]
@daniarherikurniawan lets use this PR https://github.com/Seagate/cortx-hare/pull/1681 for this issue as we do not want to remove some files which are created by make files. Here we are handling using the command and installing rpms other than cortx-motr-test *.rpms.

**Comment by daniarherikurniawan** [comment]
@vaibhavparatwar  Okay, that would work! :)
I will close another PR.

**Comment by vaibhavparatwar** [comment]
Closing this updated README with the link to motr QSG for building & installing Motr rpms
