### ISSUE TITLE
Facter >= 3.14.8 is needed by cortx-hare

### ISSUE THREAD

**Issue by daniarherikurniawan** [Seagate/cortx-hare#1665]
I am following the readme to install Hare, and when I run `sudo rpm -ivh ~/rpmbuild/RPMS/x86_64/cortx-hare-*.rpm`, I got this error:
``` sh
error: Failed dependencies:
	facter >= 3.14.8 is needed by cortx-hare-1.0.1-1_git986375b.el7.x86_64
```

I haven't found a way to satisfy that requirement. Also, according to this https://pkgs.org/download/facter, the most up-to-date facter is at version 3.14.2. Is that specific version is crucial? and how to correctly install that package?

Thanks

**Comment by vaibhavparatwar** [comment]
This issue has already been worked on. Its going to be fixed soon. Thanks @daniarherikurniawan already PR is in review

**Comment by daniarherikurniawan** [comment]
Thanks! I will close this issue now.

**Comment by daniarherikurniawan** [comment]
I am reopening this issue since the issue hasn't been solved.

**Comment by vaibhavparatwar** [comment]
@daniarherikurniawan  yes this PR is still under review from hare side cc @mssawant

**Comment by johnbent** [comment]
@vaibhavparatwar , what is the status of this please?  @madhavemuri , do you know anything about this?

**Comment by madhavemuri** [comment]
> @vaibhavparatwar , what is the status of this please? @madhavemuri , do you know anything about this?

I think docker release repo build (available to community as well) provides ../3rd_party/hare-uploads/puppet-agent-6.13.0-1.el7.x86_64.rpm, using which hare can be installed without this Facter issue.

@vaibhavparatwar @johnbent : ^

**Comment by darkryder** [comment]
@madhavemuri Can you please point me to this docker release repo build? I've been struggling w/ the same problem.

**Comment by johnbent** [comment]
Hey @darkryder .  @andriytk has worked hard to make motr available as a more easily testable release.  You might take a look at [https://github.com/Seagate/cortx-motr/releases/tag/untagged-624b9349bbd4914f0ba5](https://github.com/Seagate/cortx-motr/releases/tag/untagged-624b9349bbd4914f0ba5) which might be an easier way to get you up and running.  Oh, that might only work for single node though; I'm not sure.

**Comment by darkryder** [comment]
Hi @johnbent, thanks for pointing it out. Unfortunately, that link 404s for me. Also, `624b9349bbd4914f0ba5` doesn't seem like an accessible commit in the cortx-motr directory(at least publicly). Can you please verify this? I wonder if github has a notion of private releases.

The latest one I see is [CORTX-OVA-2.0.0-264](https://github.com/Seagate/cortx-motr/releases/tag/CORTX-OVA-2.0.0-264).

**Comment by andriytk** [comment]
@darkryder , try this one - https://github.com/Seagate/cortx-motr/releases/tag/ova-centos79

**Comment by johnbent** [comment]
Thanks both!  Not sure where that came from.  Fixing it in the parent quick start guide too.  :)

**Comment by madhavemuri** [comment]
> @madhavemuri Can you please point me to this docker release repo build? I've been struggling w/ the same problem.

https://github.com/Seagate/cortx/blob/main/doc/community-build/Generate-Cortx-Build-Stack.md
Centos 7.9 docker image too is available at https://github.com/Seagate/cortx/pkgs/container/cortx-build
They are being used for io stack rpm (generated through docker ... make io-stack) installation in perfline and are working fine without this issue.

**Comment by daniarherikurniawan** [comment]
Thank you guys! I closed this issue because @vaibhavparatwar PR solved it!
