### ISSUE TITLE
Dynamic pools to be added

### ISSUE THREAD

**Issue by andriytk** [Seagate/cortx-hare#1741]
Hare should allow to add/remove pools with different disks/nodes to/from the configuration dynamically without restarting the cluster. The request came from IO-SEA project, but it will be beneficial for Lyve Cloud as well to be able to grow the cluster online.

**Comment by mssawant** [comment]
@andriytk, this is a new feature requirement and would require designing and planning. To understand correctly, do you mean an interface to select devices from the cluster and form a pool out of those? Will aux-pool feature suffice your needs as that feature is already present. Auxiliary pools are created with different combinations of cluster devices having different N but same K layout parameters.

**Comment by cortx-admin** [comment]
> Vaibhav Prakash Paratwar commented in Jira Server:

Improvement / Refactoring (Design) cc [~520513]

**Comment by cortx-admin** [comment]
> Vaibhav Prakash Paratwar commented in Jira Server:

[~520414] [~532357][~517711][~535110] - Need some help from Architects and PLM to understand the requirement of this feature and MVP if we take this up. We are changing this to a story for now (may be this will be a epic if large changes are required). [~211146] [~519455] We need general guidance for enhancement requests coming in from community and how do we accommodate in our process. cc [~520513][~520478]

**Comment by cortx-admin** [comment]
> Ujjwal Lanjewar commented in Jira Server:

[~534380] We need to define what customer problem or use case this solves and only then we can comment if this is required. Please change the title and description of the ticket with these details.

**Comment by cortx-admin** [comment]
> Vaibhav Prakash Paratwar commented in Jira Server:

[~520414] Could you please help with the use cases ? Or get it from IO-SEA project stake holders ?

**Comment by cortx-admin** [comment]
> Donald R Bloyer commented in Jira Server:

[~752394] [~533209] [~535110]

Hey guys, so need you help here (and Gregory, I konw you are in different role now, but a lot of this was defined/prioritized under your watch ;))

We need to understand how Dynamic Pools really fits into the overall business strategy for CORTX, AND what is its prioritization relative First MVP vs later improvement features.  Thanks!!

**Comment by cortx-admin** [comment]
> Donald R Bloyer commented in Jira Server:

The response from Gregory (concurred by Pete) indicates this is targeted post MVP, ie first update release after initial MVP.  

[7/22 11:20 AM] Gregory Touretsky

From [https://seagate-systems.atlassian.net/wiki/spaces/PRIVATECOR/pages/563577180/CORTX-Cloud+Product+Requirements+Document+PRD]:

!image-2022-07-26-04-15-30-175.png!

So we agreed in the past that the {color:#de350b}first version of Lyve Rack may go out without this functionality, but it's important to add it soon after. I remember setting the expectation of not more than 6 months between the first release without capacity growth and the following one which has this functionality{color}

**Comment by shailesh-vaidya** [comment]
Closing as an obsolete
