### ISSUE TITLE
[Mini Provisioner] Sample files don't use dix pool type

### ISSUE THREAD

**Issue by knekrasov** [Seagate/cortx-hare#1742]
@knekrasov 
I think it would be nice to add 1 dix pool as well to all the sample files.
Currently we just have sns.
Thanks!

_Originally posted by @suvratjoshi in https://github.com/Seagate/cortx-hare/issues/1739#issuecomment-892536417_

**Comment by vaibhavparatwar** [comment]
@suvratjoshi can we add dix pool parameters in template files as part of EOS-16272 PR?

**Comment by suvratjoshi** [comment]
Yes right.
I was already about to do that. :)

**Comment by suvratjoshi** [comment]
In review : 
PR : https://github.com/Seagate/cortx-hare/pull/1651

**Comment by cortx-admin** [comment]
> Suvrat Chandrashekhar Joshi commented in Jira Server:

Patch for these dix pool related additions to sample files, is combined with aux pools' PR :
https://github.com/Seagate/cortx-hare/pull/1651

Thanks!

**Comment by suvratjoshi** [comment]
The PR #1651 is merged to fault_tolerance branch, which included changes for this request as well.
This issue is covered using JIRA ticket https://jts.seagate.com/browse/EOS-23822
Marking this issue as resolved.
Thanks!

**Comment by cortx-admin** [comment]
> Suvrat Chandrashekhar Joshi commented in Jira Server:

PR https://github.com/Seagate/cortx-hare/pull/1651 is merged to fault_tolerance branch.
Thanks!

**Comment by cortx-admin** [comment]
> Pavan Krishna Thunuguntla commented in Jira Server:

Verified by deploying and test (TEST-26881) *PR#1651*

[Custom-CI#2560|http://cortx-storage.colo.seagate.com/releases/cortx/github/integration-custom-ci/centos-7.8.2003/custom-build-2560]
