### ISSUE TITLE
Error mkdir: cannot create directory 'vendor': Permission denied when running sudo make install

### ISSUE THREAD

**Issue by kiwionly2** [Seagate/cortx-hare#1751]
Hi, I encounter an error when running 

`sudo make install` for hare

![image](https://user-images.githubusercontent.com/77140436/128881615-c26ac68a-1b9d-4ebb-943e-92b6bfb046d8.png)

any idea?

**Comment by hessio** [comment]
Hi @kiwionly2 just checking to see if I can close this issue?

**Comment by kiwionly2** [comment]
Hi hessio, seem like I miss out your message.

I follow the [README](https://github.com/Seagate/cortx-utils/blob/main/py-utils/README.md) guide to install py-utils, some how I not sure is it install success.

I try to verify as follow: 

![image](https://user-images.githubusercontent.com/77140436/129581925-02210e84-1915-4f57-97df-bc112630c9c0.png)

but seem like no luck.

Any hint for py-utils installation ?

**Comment by hessio** [comment]
You need to use python3 instead of python

**Comment by kiwionly2** [comment]
Ok, look good.

![image](https://user-images.githubusercontent.com/77140436/129582745-0d341e62-4caf-4456-97bc-39cfd30fda18.png)

However I still encounter the same error when try to run `sudo make install` on hare. When run `make` everything ok.

![image](https://user-images.githubusercontent.com/77140436/129583213-cd2f1c62-9467-4f1c-9f64-2dccd2313a3a.png)

**Comment by hessio** [comment]
I think you need to use the /root directory because of the rules of the Seagate ssc vm's. There is something called `root_squash NFS server`, if you search that you can try to understand what this is. Run `df` to see whether your home dir is on NFS mount or not.

**Comment by kiwionly2** [comment]
For ssc vm, it is should all be NFS. 

After `df` I saw something like `ssc-nfs-home1.colo.seagate.com:/home/<gid>` which mount to /home/<gid>.

I switch to root to `make` and `sudo make install`, and it had running successfully.

Thanks !

**Comment by hessio** [comment]
Yes exactly you cannot run the `make` and `sudo make install` from one of these directories `ssc-nfs-home1.colo.seagate.com:/home/<gid>` that is why it works when you switch to `/root`
