### ISSUE TITLE
/opt/seagate path is available outside of seagate?

### ISSUE THREAD

**Issue by johnbent** [Seagate/cortx-hare#1789]
Hello,

In [https://github.com/Seagate/cortx-hare/blob/main/README.md,](https://github.com/Seagate/cortx-hare/blob/main/README.md,) it says that '/opt/seagate/cortx/hare/bin is in \<user>'s PATH'. If someone does not have this in their path, how can they add it to the path?

Thanks,

**Comment by hessio** [comment]
Well my understanding is that if you don not have this file in that path when you get to this step then you have completed the steps above correctly, so maybe we can say this as a note in the guide?

**Comment by vaibhavparatwar** [comment]
@johnbent could you please check above comment and let me know if still we need to add note in the README?

**Comment by vaibhavparatwar** [comment]
@johnbent thank you. This may not be required. will close the issue.

**Comment by cortx-admin** [comment]
> Vaibhav Prakash Paratwar commented in Jira Server:

.
