### ISSUE TITLE
Problem for building and installing Hare 

### ISSUE THREAD

**Issue by lia54** [Seagate/cortx-hare#1791]
I am trying to setup a CORTX cluster and I tried to build and install HARE following the Hare User Guide from this link: https://github.com/Seagate/cortx-hare and I am getting stuck in the build and install section.
The error comes when trying to run the sudo make install command, I am getting permission error when trying to access a file inside /opt/seagate/cortx directory even when using sudo permission. 
I tried to access manually that file and I was able to open and read the file. 
Anyone has had this issue before?

**Comment by hessio** [comment]
Can you post the issue you are getting? Usually what happens is that when the installation is not completed this file is not created.

**Comment by hessio** [comment]
Also are you using a Seagate SSC VM ? This can cause an issue too if you are not running the VM as root? and if you are can you send me the ip address so I can log in to and have a look?

**Comment by hessio** [comment]
Also are you using a Seagate SSC VM ? This can cause an issue too if you are not running the VM as root? and if you are can you send me the ip address so I can log in to and have a look?

**Comment by lia54** [comment]
I am not using a VM right now. I am running on a Seagate HW server. 
This is the error I am getting after running $make install on the hare folder.
![permission_error](https://user-images.githubusercontent.com/28118432/133297382-13e1208e-19c4-4a05-955d-4c7185419507.PNG)

**Comment by lia54** [comment]
After running with sudo I am getting Permission Denied for the Makefile as well.

**Comment by knekrasov** [comment]
@lia54 Both `make install` and `make devinstall` require root access (because both of the commands will write to `/opt/seagate` and to other system folders.

> After running with sudo I am getting Permission Denied for the Makefile as well.

Can you post your command and the output, please?

I know that at SSC VMs home folder is a mounted NFS drive, where root user is not able to write to. Is your home folder also a mounted drive?

**Comment by lia54** [comment]
@knekrasov I tried with sudo and this is the error I am getting
![permission_denied](https://user-images.githubusercontent.com/28118432/133298650-77f5259a-11df-4b1b-949b-2dd54f531151.PNG)
even though I have executable permission for the Makefile.
 
-I know that at SSC VMs home folder is a mounted NFS drive, where root user is not able to write to. Is your home folder also a mounted drive?

Yes, my home folder is a mounted NFS4 drive. I have root permission, but I checked and the drive is mounted only with rw permission.

**Comment by knekrasov** [comment]
@lia54 It's an infrastructural problem then, not a software issue.

As a workaround, please try to build cortx-hare outside of your home folder (so that `sudo` will be permitted).
For instance:
1. `sudo mkdir -p /mnt/projects`
2. `sudo chown -R $(id -u) /mnt/projects`
3. `cd /mnt/projects`
4. Clone cortx-hare and cortx-motr and build cortx-hare

**Comment by hessio** [comment]
Oh ok so then this is the issue I believe, you will need to do `sudo su -` this will allow you change to root user from there if you run the commands this should work.

**Comment by lia54** [comment]
Thank you @knekrasov! 
I was able to build and install cortx-motr and hare in the /mnt/projects folder as you suggested.
Thanks @hessio for your help as well!

**Comment by cortx-admin** [comment]
> Vaibhav Prakash Paratwar commented in Jira Server:

As per comments, closing this as this is resolved now.

**Comment by cortx-admin** [comment]
> Vaibhav Prakash Paratwar commented in Jira Server:

.

**Comment by cortx-admin** [comment]
> Vaibhav Prakash Paratwar commented in Jira Server:

.
