### ISSUE TITLE
hax/ha/events.py:23: error: Skipping analyzing "cortx.utils.message_bus": found module but no type hints or library stubs

### ISSUE THREAD

**Issue by andriytk** [Seagate/cortx-hare#1820]
When building on CentOS 8:

```
--> Checking cfgen
Success: no issues found in 1 source file
running flake8
WARNING: flake8 setuptools integration is deprecated and scheduled for removal in 4.x.  For more information, see https://gitlab.com/pycqa/flake8/issues/544
running mypy
hax/ha/events.py:23: error: Skipping analyzing "cortx.utils.message_bus": found module but no type hints or library stubs
hax/ha/events.py:23: note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports
Found 1 error in 1 file (checked 26 source files)

error: Mypy returned 1. Exiting with FAILURE status
make[1]: *** [Makefile:507: lint-hax] Error 1
make: *** [Makefile:73: build] Error 2
```

VM to reproduce can be taken from here - https://github.com/andriytk/cortx-motr/releases/tag/centos83ova.

**Comment by knekrasov** [comment]
Hi @andriytk, I tried to reproduce the issue at Centos 7.9 against the freshest cortx-py-utils but everythin went smoothly.

Unfortunately I don't have VBox installed where I can run your ova image to debug deeper. Maybe you have a machine where I can ssh to? 

Do you use cortx-hare from main branch, BTW?

**Comment by andriytk** [comment]
Yes, from the latest main branch.

**Comment by mssawant** [comment]
@andriytk, you need to install cortx-py-utils package. cc @pavankrishnat, @vaibhavparatwar

**Comment by pavankrishnat** [comment]
@andriytk,  can you please re-verify by installing cortx-py-utils and close if working.

**Comment by andriytk** [comment]
Yes, the installed `cortx-py-utils` package seems to fix this issue.

**Comment by cortx-admin** [comment]
> Vaibhav Prakash Paratwar commented in Jira Server:

.

**Comment by cortx-admin** [comment]
> Vaibhav Prakash Paratwar commented in Jira Server:

.
