### ISSUE TITLE
hax TypeError: Object of type StobIoqError is not JSON serializable on disk failure

### ISSUE THREAD

**Issue by andriytk** [Seagate/cortx-hare#1830]
{noformat}
Oct 12 19:27:44 sage-tier3-1 kernel: sd 0:0:12:0: [sdl] tag#17 FAILED Result: hostbyte=DID_OK driverbyte=DRIVER_SENSE cmd_age=4s
Oct 12 19:27:44 sage-tier3-1 kernel: sd 0:0:12:0: [sdl] tag#17 Sense Key : Medium Error [current] [descriptor] 
Oct 12 19:27:44 sage-tier3-1 kernel: sd 0:0:12:0: [sdl] tag#17 Add. Sense: Unrecovered read error
Oct 12 19:27:44 sage-tier3-1 kernel: sd 0:0:12:0: [sdl] tag#17 CDB: Read(32)
Oct 12 19:27:44 sage-tier3-1 kernel: sd 0:0:12:0: [sdl] tag#17 CDB[00]: 7f 00 00 00 00 00 00 18 00 09 20 00 00 00 00 00
Oct 12 19:27:44 sage-tier3-1 kernel: sd 0:0:12:0: [sdl] tag#17 CDB[10]: 00 00 5c 80 00 00 5c 80 00 00 00 00 00 00 00 80
Oct 12 19:27:44 sage-tier3-1 kernel: blk_update_request: critical medium error, dev sdl, sector 190296
Oct 12 19:27:44 sage-tier3-1 motr-server[2385]: motr[02385]:  f830   WARN  [stob/ioq.c:443:ioq_io_error]  IO error: stob_id={<100000000000000:adf11e>,<100000000000000:3f>} conf_sdev=<6400000000000001:111>
Oct 12 19:27:44 sage-tier3-1 hare-hax[1709]: motr[01709]:  2800   WARN  [ha/halon/interface.c:409:halon_interface_msg_received_cb]  hl=0x7f8f50044070 ep=172.18.1.7@o2ib:12345:2:2 epoch=0 tag=80 type=1
Oct 12 19:27:44 sage-tier3-1 hare-hax[1709]: motr[01709]:  c670   WARN  [hax.c:433:handle_stob_ioq]  Got STOB_IOQ
Oct 12 19:27:44 sage-tier3-1 hare-hax[1709]: 2021-10-12 19:27:44,979 [INFO] {Dummy-1} fid=0x6400000000000001:0x111, sie_conf_sdev=0x6400000000000001:0x111
Oct 12 19:27:44 sage-tier3-1 hare-hax[1709]: motr[01709]:  c5e0   WARN  [ha/halon/interface.c:1135:m0_halon_interface_delivered]  hl=0x7f8f50044070 ep=172.18.1.7@o2ib:12345:2:2 epoch=0 tag=80 type=1
Oct 12 19:27:44 sage-tier3-1 hare-hax[1709]: 2021-10-12 19:27:44,980 [DEBUG] {qconsumer-1} Got StobIoqError(group=81597, fid=0x6400000000000001:0x111, conf_sdev=0x6400000000000001:0x111, stob_id=StobId(domain_fid=0x100000000000000:0xadf11e, fid=0x100000000000000:0x3f), fd=46, opcode=1, rc=18446744073709551611, offset=96468992, size=1048576, bshift=12) message from planner
Oct 12 19:27:44 sage-tier3-1 hare-hax[1709]: 2021-10-12 19:27:44,980 [INFO] {qconsumer-1} Stob IOQ: 0x6400000000000001:0x111
Oct 12 19:27:44 sage-tier3-1 hare-hax[1709]: 2021-10-12 19:27:44,981 [ERROR] {qconsumer-1} **ERROR**
Oct 12 19:27:44 sage-tier3-1 hare-hax[1709]: Traceback (most recent call last):
Oct 12 19:27:44 sage-tier3-1 hare-hax[1709]: File "/opt/seagate/cortx/hare/lib64/python3.6/site-packages/hax/handler.py", line 227, in _do_work
Oct 12 19:27:44 sage-tier3-1 hare-hax[1709]: payload = dump_json(item)
Oct 12 19:27:44 sage-tier3-1 hare-hax[1709]: File "/opt/seagate/cortx/hare/lib64/python3.6/site-packages/hax/util.py", line 1492, in dump_json
Oct 12 19:27:44 sage-tier3-1 hare-hax[1709]: return simplejson.dumps(obj, for_json=True)
Oct 12 19:27:44 sage-tier3-1 hare-hax[1709]: File "/opt/seagate/cortx/hare/lib64/python3.6/site-packages/simplejson/__init__.py", line 412, in dumps
Oct 12 19:27:44 sage-tier3-1 hare-hax[1709]: **kw).encode(obj)
Oct 12 19:27:44 sage-tier3-1 hare-hax[1709]: File "/opt/seagate/cortx/hare/lib64/python3.6/site-packages/simplejson/encoder.py", line 296, in encode
Oct 12 19:27:44 sage-tier3-1 hare-hax[1709]: chunks = self.iterencode(o, _one_shot=True)
Oct 12 19:27:44 sage-tier3-1 hare-hax[1709]: File "/opt/seagate/cortx/hare/lib64/python3.6/site-packages/simplejson/encoder.py", line 378, in iterencode
Oct 12 19:27:44 sage-tier3-1 hare-hax[1709]: return _iterencode(o, 0)
Oct 12 19:27:44 sage-tier3-1 hare-hax[1709]: File "/opt/seagate/cortx/hare/lib64/python3.6/site-packages/simplejson/encoder.py", line 273, in default
Oct 12 19:27:44 sage-tier3-1 hare-hax[1709]: o.__class__.__name__)
Oct 12 19:27:44 sage-tier3-1 hare-hax[1709]: TypeError: Object of type StobIoqError is not JSON serializable
Oct 12 19:27:44 sage-tier3-1 hare-hax[1709]: 2021-10-12 19:27:44,982 [DEBUG] {qconsumer-1} Waiting for the next message
{noformat}

**Comment by cortx-admin** [comment]
> Vaibhav Prakash Paratwar commented in Jira Server:

.

**Comment by cortx-admin** [comment]
> Vaibhav Prakash Paratwar commented in Jira Server:

Closing this as its merged
