### ISSUE TITLE
panic: !rep->hae_disconnected_previously at ha_entrypoint_state_cb() when a client app re-started too fast

### ISSUE THREAD

**Issue by andriytk** [Seagate/cortx-hare#1842]
When a client app re-started immediately on the same endpoint - the following panic is observed:

```
./c0rm 7216978495084578698 13820138382460497882 -y
success! object deleted!!
c0rm success
./c0rm 8545206164946530277 2392405607113976076 -y
motr[05254]:  69f0   WARN  [ha/link.c:1285:ha_link_outgoing_fop_replied]  rc=-67 nr=1 hl=0x238d7b0 ep=172.18.1.23@o2ib:12345:1:1 lq_tags=(confirmed=2 delivered=2 next=2 assign=4)
motr[05254]:  69f0   WARN  [ha/link.c:1289:ha_link_outgoing_fop_replied]  old_rc=0 old_nr=0 hl=0x238d7b0 ep=172.18.1.23@o2ib:12345:1:1
motr[05254]:  68f0  FATAL  [lib/assert.c:50:m0_panic]  panic: !rep->hae_disconnected_previously at ha_entrypoint_state_cb() (ha/ha.c:310)  [git: 2.0.0-307-17-g7686dc3] 
Motr panic: !rep->hae_disconnected_previously at ha_entrypoint_state_cb() ha/ha.c:310 (errno: 0) (last failed: none) [git: 2.0.0-307-17-g7686dc3] pid: 5254  
Motr panic reason: HA has already decided that this process has failed. There is no good reason to continue doing something, and there is no code yet to handle graceful shutdown in this case. Let's just terminate the process and let HA do it's job.
```

**Comment by vaibhavparatwar** [comment]
@andriytk  can you confirm if you have seen this issue recently? can we close this?

**Comment by vaibhavparatwar** [comment]
@andriytk yes, @mssawant's analysis says that this issue is not seen in recent builds. Please check https://jts.seagate.com/browse/EOS-25567?focusedCommentId=2235623&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-2235623 in JIRA. i just wanted to confirm as you are the reporter for this issue. thanks.

**Comment by andriytk** [comment]
I wonder if it was tested by the scenario that is described above in the issue description.

**Comment by cortx-admin** [comment]
> Mandar Sawant commented in Jira Server:

This is not reproduced in the latest several deployments and expected to be fixed.

**Comment by cortx-admin** [comment]
> Vaibhav Prakash Paratwar commented in Jira Server:

[~520414] can you please help here? is this issue seen in recent builds?

**Comment by andriytk** [comment]
It's seen on the sage-2.1 branch installed on the Sage prototype cluster - yes. If it is fixed in the main branch - let me know the commit id which fixes it and is not present in sage-2.1 branch so that I could cherry pick it there. Thanks.

**Comment by mssawant** [comment]
@andriytk, Kubernetes branch is now merged to main and `hctl bootstrap` is working as well, can you please try to rebase `sage` branch on `cortx-hare` main branch and try? cc @vaibhavparatwar .

**Comment by cortx-admin** [comment]
> Pavan Krishna Thunuguntla commented in Jira Server:

This particular panic was fixed in [EOS-19409: motr-mkfs fails with Motr panic: !rep->hae_disconnected_previously by mssawant · Pull Request #1586 · Seagate/cortx-hare (github.com)|https://github.com/Seagate/cortx-hare/pull/1586] 

[~931950] please confirm with latest build and update it.

**Comment by cortx-admin** [comment]
> Supriya Chavan commented in Jira Server:

A reference file for output of mcp utility:
 [^mcpfile.log]

**Comment by cortx-admin** [comment]
> Supriya Chavan commented in Jira Server:

.

**Comment by cortx-admin** [comment]
> Supriya Chavan commented in Jira Server:

This particular panic was fixed in [EOS-19409: motr-mkfs fails with Motr panic: !rep->hae_disconnected_previously by mssawant · Pull Request #1586 · Seagate/cortx-hare (github.com)|https://github.com//pull/1586]

**Comment by cortx-admin** [comment]
> Supriya Chavan commented in Jira Server:

.
