### ISSUE TITLE
Invalid cluster description for motr single node setup

### ISSUE THREAD

**Issue by kiwionly2** [Seagate/cortx-hare#1922]
Hi, 

I am trying to setup a single motr node, however I encounter this issue :

![image](https://user-images.githubusercontent.com/77140436/147654853-3a791581-110a-49e9-887d-2ee76052a414.png)

This seem like a missing key **transport_type** in the **CDF. yaml** file.

**Comment by cortx-admin** [comment]
For the convenience of the Seagate development team, this issue has been mirrored in a private Seagate Jira Server: https://jts.seagate.com/browse/EOS-27223. Note that community members will not be able to access that Jira server but that is not a problem since all activity in that Jira mirror will be copied into this GitHub issue.

**Comment by mssawant** [comment]
Thanks @kiwionly2, this is addressed by https://github.com/Seagate/cortx-hare/pull/1926.

**Comment by cortx-admin** [comment]
> Mandar Sawant commented in Jira Server:

review at https://github.com/Seagate/cortx-hare/pull/1926

**Comment by mssawant** [comment]
@kiwionly2, https://github.com/Seagate/cortx-hare/pull/1926 is merged to main, can you please re-verify and close if working?

**Comment by cortx-admin** [comment]
> Mandar Sawant commented in Jira Server:

https://github.com/Seagate/cortx-hare/pull/1926 merged to main.

**Comment by kiwionly2** [comment]
@mssawant 

I change **transport_key** to **lnet** ( could you confirm is this correct value ? ) since I not using **libfab**.

however after staring hare, I encounter this issue ( which I had open  in issue #1924 )

Here the screenshot:

![image](https://user-images.githubusercontent.com/77140436/147807101-3fd47886-daa3-4972-a3a4-aa39327cab90.png)

Any idea ?

**Comment by cortx-admin** [comment]
> Vaibhav Prakash Paratwar commented in Jira Server:

.
