### ISSUE TITLE
Error when running /opt/seagate/cortx/hare/bin/../bin/cfgen --help-schema

### ISSUE THREAD

**Issue by kiwionly2** [Seagate/cortx-hare#1923]
Hi, 

I am trying to run  `/opt/seagate/cortx/hare/bin/../bin/cfgen --help-schema`

However , I keep encounter python module error , so far I had install **psutil**, and **hax** module, however still encounter this error:

![image](https://user-images.githubusercontent.com/77140436/147655314-e2b9aea7-8b85-4851-9585-03cb076a00de.png)

any idea ?

**Comment by cortx-admin** [comment]
For the convenience of the Seagate development team, this issue has been mirrored in a private Seagate Jira Server: https://jts.seagate.com/browse/EOS-27224. Note that community members will not be able to access that Jira server but that is not a problem since all activity in that Jira mirror will be copied into this GitHub issue.

**Comment by ydb242** [comment]
@kiwionly2 Can you tell me what steps did you follow for deploying the cluster?

**Comment by kiwionly2** [comment]
@ydb242 

I just follow **hare** documentation instruction for **hare** installation, I encounter error and try to run this command, some how I get an error.

**Comment by ydb242** [comment]
Ok.
You can do one thing to mitigate this error.
Kindly start the python virtual environment using the following command.
`source /root/cortx-hare/.py3env/bin/activate`
Once in the virtual environment, try running the command. 
It should run without any issue.
Note: /root/cortx-hare is the path to hare directory used to start the cluster.

**Comment by kiwionly2** [comment]
@ydb242 

I had try your suggestion, but seem like it is not working.

![image](https://user-images.githubusercontent.com/77140436/147831495-4edce557-e0f7-4562-b348-258055d1fcb5.png)

**Comment by kiwionly2** [comment]
I try to reinstall a fresh new motr and hare in a new vm, however, still encounter error.

Here the error if running in python virtual environment:

![image](https://user-images.githubusercontent.com/77140436/148333191-b7f97cda-ab4f-4df9-8d6a-0111ef97807a.png)

While this is the one running normal ( without using virtual environment)

![image](https://user-images.githubusercontent.com/77140436/148333443-2dbc137f-77b6-4a32-9659-f1022d701b87.png)

**Comment by kiwionly2** [comment]
With help from @ydb242 , **motr** and **hare** is reinstall again and now **cfgen** is working if run in **python virtual environment**.

![image](https://user-images.githubusercontent.com/77140436/148337377-b7c2462e-dcc4-4d87-aa95-c44c0c448f39.png)

However without virtual environment, the error still remain.

![image](https://user-images.githubusercontent.com/77140436/148337830-176fa061-d95c-4c57-8af7-f07afe14a4ca.png)


Hence suggest that perhaps can put this in troubleshooting section, if unable to running **cfgen**, could try to running **cfgen** in **python virtual environment**.

**Comment by cortx-admin** [comment]
> Yash Bhamare commented in Jira Server:

The error has now been resolved by the use of python virtual environment.
The user was trying to execute cfgen script using the normal motr + hare dev environment.
Since cfgen may not have the knowledge of all the modules with it, using python virtual environment helps finding the necessary path of the modules. This prevents any error while running the cfgen script.

**Comment by cortx-admin** [comment]
> Vaibhav Prakash Paratwar commented in Jira Server:

.

**Comment by cortx-admin** [comment]
> Vaibhav Prakash Paratwar commented in Jira Server:

Closing as community issue reporter closed github issue.
