### ISSUE TITLE
s3bench I/O start failing for 16Mb-200Sessions-12KObjects on 1node-MGW

### ISSUE THREAD

**Issue by rajeshdesh** [Seagate/cortx-hare#1958]
On a single node MGW cluster deployed on RockyLinux with 5 additional disks for data, I was running s3bench with configuration like
for OBJECTSIZE in '1Kb' '64Kb' '256Kb' '1Mb' '8Mb' '16Mb' '128Mb'; do
for SESSION in 100 200; do

This test executed well till 16MB-100 Sessions and started failing for 200 sessions post PUT of 20th object.
I tried restarting RGW with ../src/stop.sh and ../src/vstart.sh that resulted in offline m0_client as reported at 
https://github.com/Seagate/cortx-hare/issues/1957
Post recovery, observed I/O failure again for same test.

**Comment by cortx-admin** [comment]
For the convenience of the Seagate development team, this issue has been mirrored in a private Seagate Jira Server: https://jts.seagate.com/browse/EOS-27774. Note that community members will not be able to access that Jira server but that is not a problem since all activity in that Jira mirror will be copied into this GitHub issue.

**Comment by vaibhavparatwar** [comment]
@rajeshdesh  please verify it again and comment.

**Comment by rajeshdesh** [comment]
yes @vaibhavparatwar , not hitting this issue with latest build.

**Comment by rajeshdesh** [comment]
Hi @vaibhavparatwar , I am not able to reproduce the issue with latest build.
So, closing the issue. 
` Object Size  Samples  Sessions  Iteration  Write Tput  Read Tput  Write Latency  Read Latency  Write TTFB  Read TTFB  Write TTFB(99%)  Read TTFB(99%)  Write Errors  Read Errors
 -----------  -------  --------  ---------  ----------  ---------  -------------  ------------  ----------  ---------  ---------------  --------------  ------------  -----------
         4KB    10000       200          1       1.324      1.155          0.586         0.481       0.586      0.448            9.626           5.067             0            0
         4KB    10000       200          2       1.592      1.100          0.487         0.474       0.487      0.448            7.865           4.382             0            0
         4KB    10000       200          3       1.616      1.152          0.478         0.464       0.478      0.434            8.158           4.505             0            0
        16KB    10000       200          1       5.410      4.987          0.487         0.483       0.487      0.450            7.468           5.162             0            0
        16KB    10000       200          2       6.489      4.381          0.478         0.480       0.478      0.448            7.670           5.115             0            0
        16KB    10000       200          3       4.353      4.520          0.492         0.488       0.492      0.454            6.934           5.501             0            0
        63KB    10000       200          1      24.927     19.275          0.498         0.495       0.498      0.457            6.560           5.686             0            0
        63KB    10000       200          2      24.978     21.245          0.497         0.487       0.497      0.440            6.573           6.673             0            0
        63KB    10000       200          3      24.953     20.340          0.497         0.491       0.497      0.440            6.972           6.758             0            0
       256KB    10000       200          1      88.372     92.258          0.563         0.540       0.563      0.331            4.725           4.293             0            0
       256KB    10000       200          2      89.072     74.996          0.558         0.544       0.558      0.401            4.521           5.058             0            0
       256KB    10000       200          3      89.400     92.177          0.556         0.541       0.556      0.320            4.804           3.698             0            0
         1MB    10000       200          1     247.355    266.376          0.803         0.750       0.803      0.214            2.897           1.604             0            0
         1MB    10000       200          2     249.181    265.147          0.797         0.754       0.797      0.206            2.713           1.526             0            0
         1MB    10000       200          3     250.079    264.315          0.794         0.756       0.794      0.207            2.713           1.551             0            0
        16MB    10000       200          1     396.856    393.320          7.986         8.134       7.986      0.601            8.910           4.265             0            0
        16MB    10000       200          2     400.359    399.690          7.915         8.005       7.915      0.601            8.853           4.730             0            0
        16MB    10000       200          3     400.632    398.807          7.911         8.022       7.911      0.623            9.095           4.571             0            0
       128MB    10000       200          1     422.355    415.372         60.429        61.620      60.429      8.708           63.568          35.483             0            0
       128MB    10000       200          2     418.306    412.328         60.996        62.076      60.996      7.191           64.075          33.779             0            0
       128MB    10000       200          3     416.172    406.601         61.317        62.913      61.317      5.911           65.196          41.953             0            0
`

**Comment by cortx-admin** [comment]
> Rajesh Deshmukh commented in Jira Server:

Unable to reproduce the bug with single node cluster having build: 

{noformat}
[root@smxxxx run1]# cat /root/cortx-k8s/k8_cortx_cloud/solution.yaml | grep cortx
    name: cortx-secret
    cortxcontrol: ghcr.io/seagate/cortx-all:2.0.0-714
    cortxdata: ghcr.io/seagate/cortx-all:2.0.0-714
    cortxserver: ghcr.io/seagate/cortx-rgw:2.0.0-714
    cortxha: ghcr.io/seagate/cortx-all:2.0.0-714
    cortxclient: ghcr.io/seagate/cortx-all:2.0.0-714
      local: /etc/cortx
      log: /etc/cortx/log
      service_name: cortx-hax-svc
[root@smxxxx run1]#
[root@smxxxx run1]# cat summary.txt
 Object Size  Samples  Sessions  Iteration  Write Tput  Read Tput  Write Latency  Read Latency  Write TTFB  Read TTFB  Write TTFB(99%)  Read TTFB(99%)  Write Errors  Read Errors
 -----------  -------  --------  ---------  ----------  ---------  -------------  ------------  ----------  ---------  ---------------  --------------  ------------  -----------
         4KB    10000       200          1       1.324      1.155          0.586         0.481       0.586      0.448            9.626           5.067             0            0
         4KB    10000       200          2       1.592      1.100          0.487         0.474       0.487      0.448            7.865           4.382             0            0
         4KB    10000       200          3       1.616      1.152          0.478         0.464       0.478      0.434            8.158           4.505             0            0
        16KB    10000       200          1       5.410      4.987          0.487         0.483       0.487      0.450            7.468           5.162             0            0
        16KB    10000       200          2       6.489      4.381          0.478         0.480       0.478      0.448            7.670           5.115             0            0
        16KB    10000       200          3       4.353      4.520          0.492         0.488       0.492      0.454            6.934           5.501             0            0
        63KB    10000       200          1      24.927     19.275          0.498         0.495       0.498      0.457            6.560           5.686             0            0
        63KB    10000       200          2      24.978     21.245          0.497         0.487       0.497      0.440            6.573           6.673             0            0
        63KB    10000       200          3      24.953     20.340          0.497         0.491       0.497      0.440            6.972           6.758             0            0
       256KB    10000       200          1      88.372     92.258          0.563         0.540       0.563      0.331            4.725           4.293             0            0
       256KB    10000       200          2      89.072     74.996          0.558         0.544       0.558      0.401            4.521           5.058             0            0
       256KB    10000       200          3      89.400     92.177          0.556         0.541       0.556      0.320            4.804           3.698             0            0
         1MB    10000       200          1     247.355    266.376          0.803         0.750       0.803      0.214            2.897           1.604             0            0
         1MB    10000       200          2     249.181    265.147          0.797         0.754       0.797      0.206            2.713           1.526             0            0
         1MB    10000       200          3     250.079    264.315          0.794         0.756       0.794      0.207            2.713           1.551             0            0
        16MB    10000       200          1     396.856    393.320          7.986         8.134       7.986      0.601            8.910           4.265             0            0
        16MB    10000       200          2     400.359    399.690          7.915         8.005       7.915      0.601            8.853           4.730             0            0
        16MB    10000       200          3     400.632    398.807          7.911         8.022       7.911      0.623            9.095           4.571             0            0
       128MB    10000       200          1     422.355    415.372         60.429        61.620      60.429      8.708           63.568          35.483             0            0
       128MB    10000       200          2     418.306    412.328         60.996        62.076      60.996      7.191           64.075          33.779             0            0
       128MB    10000       200          3     416.172    406.601         61.317        62.913      61.317      5.911           65.196          41.953             0            0
[root@smxxxx run1]#
{noformat}

**Comment by cortx-admin** [comment]
> Vaibhav Prakash Paratwar commented in Jira Server:

Not reproducing now.

**Comment by cortx-admin** [comment]
> Vaibhav Prakash Paratwar commented in Jira Server:

.

**Comment by cortx-admin** [comment]
> Vaibhav Prakash Paratwar commented in Jira Server:

.
