### ISSUE TITLE
FDMI filter "client index" should use the first m0_client endpoint

### ISSUE THREAD

**Issue by huanghua78** [Seagate/cortx-hare#1960]
In the file: https://github.com/Seagate/cortx-hare/blob/main/cfgen/examples/singlenode.yaml#L52
From this line to the end, it's sample FDMI configuration.
```
#fdmi_filters:
#  - name: test
#    node: localhost
#    client_index: 1
#    substrings: ["Bucket-Name", "Object-Name", "Object-URI"]
```
the "client_index" is the remote FDMI plugin endpoint that FDMI events will be sent to.
For example, in the following deployment, it should the `first` m0_client endpoint, that is `inet:tcp:10.230.240.203@5001`.
```
[520428@ssc-vm-g3-rhev4-2904 cortx-hare]$ sudo hctl status
[sudo] password for 520428:
Data pool:
    # fid name
    0x6f00000000000001:0x2f 'the pool'
Profile:
    # fid name: pool(s)
    0x7000000000000001:0x4f 'default': 'the pool' None None
Services:
    localhost  (RC)
    [started]  hax        0x7200000000000001:0x6   inet:tcp:10.230.240.203@2001
    [started]  confd      0x7200000000000001:0x9   inet:tcp:10.230.240.203@3001
    [started]  ioservice  0x7200000000000001:0xc   inet:tcp:10.230.240.203@3002
    [started]  m0_client  0x7200000000000001:0x29  inet:tcp:10.230.240.203@5001
    [unknown]  m0_client  0x7200000000000001:0x2c  inet:tcp:10.230.240.203@5002

```

But the auto-generated confd.xc indicate the FDMI to use the "second" one, because in an array, index "1" is the second element.

Solution:
change the "client_index" to "0".

Please refer to: https://github.com/Seagate/cortx-motr/blob/main/fdmi/plugins/motr-fdmi-app.md
In this doc, it says to have: "client_index: 0".

I am not sure if this was original wrong, or something changed in Hare caused such issue.

**Comment by cortx-admin** [comment]
For the convenience of the Seagate development team, this issue has been mirrored in a private Seagate Jira Server: https://jts.seagate.com/browse/EOS-27780. Note that community members will not be able to access that Jira server but that is not a problem since all activity in that Jira mirror will be copied into this GitHub issue.

**Comment by cortx-admin** [comment]
> Vaibhav Prakash Paratwar commented in Jira Server:

Improvement / refactoring cc [~520513]

**Comment by cortx-admin** [comment]
> Vaibhav Prakash Paratwar commented in Jira Server:

Low priority as of now cc [~520513] [~520478]

**Comment by shailesh-vaidya** [comment]
Closing as an obsolete
