### ISSUE TITLE
hax broadcasts FAILED instead of REPAIRING for device

### ISSUE THREAD

**Issue by andriytk** [Seagate/cortx-hare#1978]
For some reason, when I try to set device to repairing state (after failed), device is still shown as failed in `hctl status` and, moreover, `hax` broadcasts FAILED instead of REPAIRING:

```
$ hctl drive-state --json $(jq --null-input --compact-output '{ node: "centos8", source_type: "drive", device: "/dev/loop1", state: "REPAIRING" }')
0
2022-02-10 18:44:02,665 [DEBUG] Bound <class 'hax.common.HaxGlobalState'> to an instance <hax.common.HaxGlobalState object at 0x7f6321d51278>
2022-02-10 18:44:02,666 [DEBUG] Created and configured an injector, config=<function di_configuration at 0x7f632110fae8>
2022-02-10 18:44:02,670 [DEBUG] Starting new HTTP connection (1): 127.0.0.1:8500
2022-02-10 18:44:02,672 [DEBUG] http://127.0.0.1:8500 "GET /v1/kv/eq-epoch HTTP/1.1" 200 104
2022-02-10 18:44:02,679 [DEBUG] http://127.0.0.1:8500 "PUT /v1/txn HTTP/1.1" 200 144
2022-02-10 18:44:02,680 [INFO] Written to epoch: 4

$ hctl status -d
Byte_count:
    critical_byte_count : 0
    damaged_byte_count : 0
    degraded_byte_count : 0
    healthy_byte_count : 0
Data pool:
    # fid name
    0x6f00000000000001:0x31 'the pool'
Profile:
    # fid name: pool(s)
    0x7000000000000001:0x51 'default': 'the pool' None None
Services:
    centos8  (RC)
    [started]  hax        0x7200000000000001:0x6   inet:tcp:192.168.180.182@2001
    [started]  confd      0x7200000000000001:0x9   inet:tcp:192.168.180.182@3001
    [started]  ioservice  0x7200000000000001:0xc   inet:tcp:192.168.180.182@3002
    [started]  m0_client  0x7200000000000001:0x29  inet:tcp:192.168.180.182@5001
    [unknown]  m0_client  0x7200000000000001:0x2c  inet:tcp:192.168.180.182@5002
Devices:
    centos8
    [online]  /dev/null
    [failed]  /dev/loop1
...
```

From syslog:

```
Feb 10 18:44:02 centos8 hare/proto-rc[2426110]: HARE_RC_EVENT_TYPE: device-state-set, HARE_RC_EVENT_PAYLOAD: {
                                                  "node": "centos8",
                                                  "source_type": "drive",
                                                  "device": "/dev/loop1",
                                                  "state": "REPAIRING"
                                                }
Feb 10 18:44:03 centos8 hare-hax[2421780]: 2022-02-10 18:44:03,219 [DEBUG] {ThreadPoolExecutor-0_0} KVGET key=bq-delivered/192.168.180.182, kwargs={}
Feb 10 18:44:03 centos8 hare-hax[2421780]: 2022-02-10 18:44:03,224 [DEBUG] {ThreadPoolExecutor-0_0} Last read epoch: 2
Feb 10 18:44:03 centos8 hare-hax[2421780]: 2022-02-10 18:44:03,225 [DEBUG] {ThreadPoolExecutor-0_0} Message #3 received: {"message_type": "M0_HA_MSG_NVEC", "payload": {"node": "centos8", "source_type": "drive", "device": "/dev/loop1", "state": "REPAIRING"}} (type: str)
Feb 10 18:44:03 centos8 hare-hax[2421780]: 2022-02-10 18:44:03,225 [DEBUG] {ThreadPoolExecutor-0_0} KVGET key=m0conf/nodes/centos8/processes, kwargs={'recurse': True}
Feb 10 18:44:03 centos8 hare-hax[2421780]: 2022-02-10 18:44:03,228 [DEBUG] {ThreadPoolExecutor-0_0} KVGET key=m0conf/nodes, kwargs={'recurse': True}
Feb 10 18:44:03 centos8 hare-hax[2421780]: 2022-02-10 18:44:03,233 [DEBUG] {ThreadPoolExecutor-0_0} KVGET key=m0conf/sites, kwargs={'recurse': True}
Feb 10 18:44:03 centos8 hare-hax[2421780]: 2022-02-10 18:44:03,238 [DEBUG] {ThreadPoolExecutor-0_0} HA broadcast, node: centos8 device: /dev/loop1 state: REPAIRING
Feb 10 18:44:03 centos8 hare-hax[2421780]: 2022-02-10 18:44:03,238 [DEBUG] {qconsumer-6} Got BroadcastHAStates(group=49, states=[HAState(fid=0x6b00000000000001:0x12, status=FAILED)], reply_to=<queue.Queue object at 0x7f9b8c70bfd0>) message from planner
Feb 10 18:44:03 centos8 hare-hax[2421780]: 2022-02-10 18:44:03,238 [INFO] {qconsumer-6} HA states: [HAState(fid=0x6b00000000000001:0x12, status=FAILED)]
Feb 10 18:44:03 centos8 hare-hax[2421780]: 2022-02-10 18:44:03,239 [DEBUG] {qconsumer-6} Broadcasting HA states [HAState(fid=0x6b00000000000001:0x12, status=FAILED)] over ha_link
```

**Comment by cortx-admin** [comment]
> Vaibhav Prakash Paratwar commented in Jira Server:

[~931950] - could you please look in to this?

**Comment by cortx-admin** [comment]
> Supriya Chavan commented in Jira Server:

On the centos machine, I was facing an issue with installing/upgrading `jq-1.6-3.el8.x86_64.rpm`.
So I tried on Rocky Linux 8.4,  and the `jq-1.6` installation was successful.

Tried to reproduce this issue:
{noformat}
[root@ssc-vm-g4-rhev4-0467 ~]# hctl status -d
Byte_count:
    critical_byte_count : 0
    damaged_byte_count : 0
    degraded_byte_count : 0
    healthy_byte_count : 0
Data pool:
    # fid name
    0x6f00000000000001:0x23 'the pool'
Profile:
    # fid name: pool(s)
    0x7000000000000001:0x3a 'default': 'the pool' None None
Services:
    ssc-vm-g4-rhev4-0467.colo.seagate.com  (RC)
    [started]  hax        0x7200000000000001:0x6   inet:tcp:10.230.244.17@22001
    [started]  confd      0x7200000000000001:0x9   inet:tcp:10.230.244.17@21001
    [started]  ioservice  0x7200000000000001:0xc   inet:tcp:10.230.244.17@21002
    [unknown]  m0_client  0x7200000000000001:0x1b  inet:tcp:10.230.244.17@21501
    [unknown]  m0_client  0x7200000000000001:0x1e  inet:tcp:10.230.244.17@21502
Devices:
    ssc-vm-g4-rhev4-0467.colo.seagate.com
    [online]  /dev/null
    [online]  /dev/sdd
    [online]  /dev/sde
    [online]  /dev/sdc

[root@ssc-vm-g4-rhev4-0467 test]# hctl drive-state --json '{"node":"ssc-vm-g4-rhev4-0467.colo.seagate.com","source_type":"drive","device":"/dev/sdc","state":"failed"}'
0
2022-02-11 04:48:47,572 [DEBUG] Bound <class 'hax.common.HaxGlobalState'> to an instance <hax.common.HaxGlobalState object at 0x7feb7f128748>
2022-02-11 04:48:47,572 [DEBUG] Created and configured an injector, config=<function di_configuration at 0x7feb82681400>
2022-02-11 04:48:47,577 [DEBUG] Starting new HTTP connection (1): 127.0.0.1:8500
2022-02-11 04:48:47,579 [DEBUG] http://127.0.0.1:8500 "GET /v1/kv/eq-epoch HTTP/1.1" 200 91
2022-02-11 04:48:47,586 [DEBUG] http://127.0.0.1:8500 "PUT /v1/txn HTTP/1.1" 200 219
2022-02-11 04:48:47,587 [INFO] Written to epoch: 2

[root@ssc-vm-g4-rhev4-0467 test]# hctl status -d
Byte_count:
    critical_byte_count : 0
    damaged_byte_count : 0
    degraded_byte_count : 0
    healthy_byte_count : 0
Data pool:
    # fid name
    0x6f00000000000001:0x23 'the pool'
Profile:
    # fid name: pool(s)
    0x7000000000000001:0x3a 'default': 'the pool' None None
Services:
    ssc-vm-g4-rhev4-0467.colo.seagate.com  (RC)
    [started]  hax        0x7200000000000001:0x6   inet:tcp:10.230.244.17@22001
    [started]  confd      0x7200000000000001:0x9   inet:tcp:10.230.244.17@21001
    [started]  ioservice  0x7200000000000001:0xc   inet:tcp:10.230.244.17@21002
    [unknown]  m0_client  0x7200000000000001:0x1b  inet:tcp:10.230.244.17@21501
    [unknown]  m0_client  0x7200000000000001:0x1e  inet:tcp:10.230.244.17@21502
Devices:
    ssc-vm-g4-rhev4-0467.colo.seagate.com
    [online]  /dev/null
    [online]  /dev/sdd
    [online]  /dev/sde
    [failed]  /dev/sdc
{noformat}

But after updating the drive state to 'REPAIRING', it is failed to update the drive state.

{noformat}
[root@ssc-vm-g4-rhev4-0467 test]# hctl drive-state --json $(jq --null-input --compact-output '{ node: "ssc-vm-g4-rhev4-0467.colo.seagate.com", source_type: "drive", device: "/dev/sdc", state: "REPAIRING" }
> ')
0
2022-02-11 04:53:29,877 [DEBUG] Bound <class 'hax.common.HaxGlobalState'> to an instance <hax.common.HaxGlobalState object at 0x7f437c55c748>
2022-02-11 04:53:29,877 [DEBUG] Created and configured an injector, config=<function di_configuration at 0x7f437fab5400>
2022-02-11 04:53:29,881 [DEBUG] Starting new HTTP connection (1): 127.0.0.1:8500
2022-02-11 04:53:29,883 [DEBUG] http://127.0.0.1:8500 "GET /v1/kv/eq-epoch HTTP/1.1" 200 93
2022-02-11 04:53:29,892 [DEBUG] http://127.0.0.1:8500 "PUT /v1/txn HTTP/1.1" 200 219
2022-02-11 04:53:29,893 [INFO] Written to epoch: 3
[root@ssc-vm-g4-rhev4-0467 test]# hctl status -d
Byte_count:
    critical_byte_count : 0
    damaged_byte_count : 0
    degraded_byte_count : 0
    healthy_byte_count : 0
Data pool:
    # fid name
    0x6f00000000000001:0x23 'the pool'
Profile:
    # fid name: pool(s)
    0x7000000000000001:0x3a 'default': 'the pool' None None
Services:
    ssc-vm-g4-rhev4-0467.colo.seagate.com  (RC)
    [started]  hax        0x7200000000000001:0x6   inet:tcp:10.230.244.17@22001
    [started]  confd      0x7200000000000001:0x9   inet:tcp:10.230.244.17@21001
    [started]  ioservice  0x7200000000000001:0xc   inet:tcp:10.230.244.17@21002
    [unknown]  m0_client  0x7200000000000001:0x1b  inet:tcp:10.230.244.17@21501
    [unknown]  m0_client  0x7200000000000001:0x1e  inet:tcp:10.230.244.17@21502
Devices:
    ssc-vm-g4-rhev4-0467.colo.seagate.com
    [online]  /dev/null
    [online]  /dev/sdd
    [online]  /dev/sde
    [failed]  /dev/sdc
{noformat}

So now I am to reproduce this issue.
cc. [~534380], [~934253]

**Comment by cortx-admin** [comment]
> Vaibhav Prakash Paratwar commented in Jira Server:

[~520478] - is this functionality (setting drive state to REPAIRING ) already available and not working OR its not yet implemented? cc [~931950] [~934253] [~940886] [~520414]

**Comment by cortx-admin** [comment]
> Mandar Sawant commented in Jira Server:

https://github.com/Seagate/cortx-hare/pull/1982 cc [~934253], [~534380]

**Comment by cortx-admin** [comment]
> Pavan Krishna Thunuguntla commented in Jira Server:

https://github.com/Seagate/cortx-hare/pull/1982

**Comment by cortx-admin** [comment]
> Mandar Sawant commented in Jira Server:

https://github.com/Seagate/cortx-hare/pull/1982 merged to main.

**Comment by cortx-admin** [comment]
> Vaibhav Prakash Paratwar commented in Jira Server:

will be verified as part of CORTX-22105
