### ISSUE TITLE
Can't see cluster size

### ISSUE THREAD

**Issue by hessio** [Seagate/cortx-hare#2125]
### Problem

"
I found that my cortx cluster can't see the storage size:
[root@ipfs4 build]# hctl status
Bytecount:
    critical : 0
    damaged : 0
    degraded : 0
    healthy : 0
But when I execute " radosgw-admin bucket stats --bucket=*** ", I can see. Although this value is also wrong.
May I ask what is the reason?
"
- taken from this issue on Slack - https://cortxcommunity.slack.com/archives/C01952XCLCF/p1655861159115379

### Expected behavior

These values shouldn't all be 0:

    critical : 0
    damaged : 0
    degraded : 0
    healthy : 0

### How to reproduce

Running this setup script:
https://github.com/Seagate/cortx-motr/blob/main/scripts/build-prep-1node-cortx-mgw.sh

### Deployment information

CentOS 8 on bare metal server

**Comment by cortx-admin** [comment]
> Vaibhav Prakash Paratwar commented in Jira Server:

.

**Comment by cortx-admin** [comment]
> Vaibhav Prakash Paratwar commented in Jira Server:

.

**Comment by cortx-admin** [comment]
> Vaibhav Prakash Paratwar commented in Jira Server:

.
