### ISSUE TITLE
I/O test failed

### ISSUE THREAD

**Issue by kimika88** [Seagate/cortx-hare#2130]
### Problem

error messages after running m0crate command: 
motr[15124]:  47c0  ERROR  [io_req.c:1551:device_check]  <! rc=-5 [0x7fc1f0056460] too many failures: nodes=0 + svcs=0 + devs=2, allowed: nodes=0 or svcs=0 or devs=0
(and more lines like this)

### Expected behavior

expecting no error

### How to reproduce

Followed this section in the user guide:
https://github.com/kimika88/cortx-hare/blob/patch-1/README.md#hare-we-go

### Deployment information

[root@ssc-vm-g4-rhev4-1317 cortx-motr]# fi_info --version
fi_info: 1.11.2
libfabric: 1.11.2
libfabric api: 1.11
[root@ssc-vm-g4-rhev4-1317 cortx-motr]# cat /etc/redhat-release
CentOS Linux release 7.9.2009 (Core)

### Additional information

[hare_ssc-vm-g4-rhev4-1317.colo.seagate.com.tar.gz](https://github.com/Seagate/cortx-hare/files/9023599/hare_ssc-vm-g4-rhev4-1317.colo.seagate.com.tar.gz)

**Comment by kimika88** [comment]
This is a duplicated issue as #2129 I submitted twice because I saw 404 error and thought I did not submit successfully.

**Comment by cortx-admin** [comment]
For the convenience of the Seagate development team, this issue has been mirrored in a private Seagate Jira Server: https://jts.seagate.com/browse/CORTX-33120. Note that community members will not be able to access that Jira server but that is not a problem since all activity in that Jira mirror will be copied into this GitHub issue.

**Comment by cortx-admin** [comment]
> Vaibhav Prakash Paratwar commented in Jira Server:

.

**Comment by cortx-admin** [comment]
> Vaibhav Prakash Paratwar commented in Jira Server:

.

**Comment by cortx-admin** [comment]
> Vaibhav Prakash Paratwar commented in Jira Server:

.
